### ISSUE TITLE
why not from PIL import Image

### ISSUE THREAD

**Issue by crcrpar** [bethgelab/foolbox#101]
I wonder why not `from PIL import Image` in https://github.com/bethgelab/foolbox/blob/master/foolbox/utils.py#L76-L78

In major open sources, they use `from PIL import Image` such as pillow official documents and pytorch/torchvision.
In addition to this, I encountered an error when using `foolbox.utils.imagenet_example` caused by `PIL.Image.open`.

**Comment by jonasrauber** [comment]
Can you clarify what you mean. Whether I do `import PIL` and then use `PIL.Image` or instead `from PIL import Image` and then use `Image` shouldn't make a difference?

**Comment by crcrpar** [comment]
In my environment, `PIL.Image` raised AttributeError: module 'PIL' has no attribute 'Image'.
This error is solved by using `from PIL import Image` instead.

my environment:
- python 3.5.3
- Pillow 5.0.0

**Comment by jonasrauber** [comment]
Interesting. Thanks for reporting this. If you want you can make a pull-request, otherwise I will fix it in a few days.

**Comment by jonasrauber** [comment]
fixed in the recently released version 0.12.4

**Comment by crcrpar** [comment]
Thank you.
