### ISSUE TITLE
SinglePixelAttack on pretrained Keras ResNet

### ISSUE THREAD

**Issue by nsrishankar** [bethgelab/foolbox#102]
Implementing a single pixel attack on a pretrained Keras ResNet (ImageNet dataset) model yields the following error:

`/home/carnd/anaconda3/envs/carnd-term1/lib/python3.5/site-packages/foolbox/attacks/base.py:102: UserWarning: SinglePixelAttack did not find an adversarial, maybe the model or the criterion is not supported by this attack.
  warnings.warn('{} did not find an adversarial, maybe the model or the criterion is not supported by this attack.'.format(self.name()))  # noqa: E501`

**Comment by jonasrauber** [comment]
The `SinglePixelAttack` can of course always fail if the model is not sensitive to single pixel perturbations (it's a very weak attack).

**Comment by nsrishankar** [comment]
Oh, so I assume that it will usually fail on the pretrained Keras models, and just succeeds on simplistic CNNs. The original paper tried it on VGG-16 and states that they have a 19% success rate, so I probably should just use something like AllConvolution or Network-in-Network.

**Comment by jonasrauber** [comment]
Yes, on ImageNet, the single pixel attack is not very effective. 
Could you tell me which paper you are referring to (where can I find the 19%)?

**Comment by nsrishankar** [comment]
Single-Pixel attack [Paper](https://arxiv.org/pdf/1710.08864.pdf) [page 6], though I skimmed through the results.
