### ISSUE TITLE
overflow encountered

### ISSUE THREAD

**Issue by MrMOABy** [bethgelab/foolbox#105]
I get the following error when just trying to run the sample code. Any thoughts on how this can be fixed?

RuntimeWarning: overflow encountered in long_scalars
  f = n * (max_ - min_)**2

**Comment by jonasrauber** [comment]
Could you please post the full error message / warning, including line numbers, stack trace, etc.

Also: which version of Python, Foolbox, NumPy are you using. Are you sure you are using the example code from the README as is or did you change anything?

**Comment by MrMOABy** [comment]
I'm not on the machine I was trying to run it on earlier, but I remember that it was from line 125 in distances.py. I know that I was running python 3.6.4 64 bit. Other versions were whatever was the latest found when installing through pycharm.

**Comment by jonasrauber** [comment]
Yes, I know it's that line, but I would still like to see the stack trace of the full error message and the version numbers once you have access to the machine again. Thanks!

**Comment by MrMOABy** [comment]
This is the only errors that I get:
Using TensorFlow backend.
2018-03-12 10:18:28.325898: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
..\AppData\Local\Programs\Python\Python36\lib\site-packages\foolbox\distances.py:125: RuntimeWarning: overflow encountered in long_scalars
  f = n * (max_ - min_)**2

**Comment by MrMOABy** [comment]
Here's a link to all my versions of libraries/python: https://imgur.com/a/QSW6t

**Comment by jonasrauber** [comment]
What's the input size of your model?
What are the values that you pass as bounds?
Could it be that you are using a 32 bit machine / system?

**Comment by jonasrauber** [comment]
This should be fixed in Foolbox 0.15.0.

@MrMOABy please still let me know your input size and model bounds, thanks!
