### ISSUE TITLE
Feature Request: Adversarial Examples on Discrete Sequences

### ISSUE THREAD

**Issue by EdwardRaff** [bethgelab/foolbox#107]
This [pre-print](https://arxiv.org/pdf/1802.04528.pdf) was recently published on an attack method for attacking networks with an embedding layer. I was hoping to do something similar in issue #80 , and so am making the feature request!

It would probably take more effort, but another thing the paper uses is attacking only a subset of the input. I think this could be interesting for a wider class of problems, and so would request that feature as well.

**Comment by jonasrauber** [comment]
Contributions in that direction are welcome.

Some aspects are already possible with Foolbox, e.g. attacking non-differentiable models using our [decision-based attacks](http://foolbox.readthedocs.io/en/latest/modules/attacks/decision.html) and enforcing discrete inputs (by adding a rounding layer before the actual input).

Attacking only a subset of the input is also already possible by modifying the model such that it get's a constant input (that's part of the model) and a modifiable input that will be fed to the attack. It might not be the most convenient way of doing this, but it should work well.

**Comment by jonasrauber** [comment]
Closing this because there are no plans to work on this and it's somewhat unclear what exactly would be needed.
