### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by ArthurConan** [bethgelab/foolbox#126]
Hi, guys! Your FoolBox is vary cool tool. But I have a question:
Is it possible to attack already trained model?
I have a KERAS model saved as "model.h5" and dataset in the form of "data.csv" on which this model was trained. Or model such as "model.ckpt"
So, can I load my model and attack with your tool?
thanks in advance!

**Comment by jonasrauber** [comment]
Of course, that's basically the main use case of Foolbox: using adversarial attacks to find adversarial examples for models.
