### ISSUE TITLE
LocalSearchAttack

### ISSUE THREAD

**Issue by ArthurConan** [bethgelab/foolbox#129]
Hi!
I just start to overcome you program)
So can you hep me with such question (I have been trying to solve it for week)
I want to see how this LocalSearch attack works with bunch of images(model/images) and model Inception_v3
Can you show how to realize it? 
Everything i tried - failed
Very thanks in advance!

**Comment by jonasrauber** [comment]
Get familiar with the example: https://github.com/bethgelab/foolbox#example
Make sure it works for you.
Replace ResNet with Inception, e.g. from Keras: https://keras.io/applications/#inceptionv3
Make sure it works (with DeepFoolAttack or FGSM)
Replace FGSM with the LocalSearchAttack.

**Comment by ArthurConan** [comment]
yeah, it works for me
But can you also give a hint how to save created adversarial images?

**Comment by jonasrauber** [comment]
It's a NumPy array. Save it like every other NumPy array or convert it to an image using e.g. Pillow. That's nothing Foolbox-specifc ;-)
Please close if solved.
