### ISSUE TITLE
Pytorch using image in CxWxH way which is consistent with TF makes preprocess not work

### ISSUE THREAD

**Issue by theFool32** [bethgelab/foolbox#135]
Pytorch using image in CxWxH way which is consistent with TF makes preprocess not work

**Comment by iacolippo** [comment]
I've successfully used `CxWxH` with `PytorchModel`. Tensorflow expects `WxHxC`. You can see it by the default value of `channel_axis` in the two classes (and the docs of the two frameworks). Can you provide a minimal working example of your issue?

**Comment by theFool32** [comment]
Below is a simple example not working
```
import foolbox
import numpy as np
import torch
from torchvision import models

p_model = models.resnet18()
preprocessing = (np.array([104, 116, 123]), 1)
fmodel = foolbox.models.PyTorchModel(p_model, bounds=(0, 255), preprocessing=preprocessing, num_classes=1000, cuda=False)

image, label = foolbox.utils.imagenet_example()

attack = foolbox.attacks.FGSM(fmodel)
adversarial = attack(image[:, :, ::-1], label)
```

Error message:
```
RuntimeError: Given groups=1, weight[64, 3, 7, 7], so expected input[1, 224, 224, 3] to have 3 channels, but got 224 channels instead
```

**Comment by iacolippo** [comment]
Oh, I actually had to fix it in the source code. It comes from how `numpy` broadcasting works (it works its way back from the trailing dimension and for every trailing dimension they must match or either of the two must be one). So if you have two arrays `a` and `b` of shape `(1, 224, 224, 3)` and `(3, )` you can do `a-b`, but  if `a.shape = (1, 3, 224, 224)` the broadcasting for `a-b` fails.
Pytorch accepts tensors in the (BxCxHxW) format.

You can make you code work by setting 

```
preprocessing = (np.array([[[[104]], [[116]], [[123]]]]), 1)
```

and

```
adversarial = attack(np.transpose(image, (2, 0, 1)), label)
```

This gives you a preprocessing array of shape `(1, 3, 1, 1)` for which the broadcasting is valid and the correct input shape `(1, 3, 224, 224)` to the pytorch model.

I think this case should be automatically detected and solved inside the source code (as it is specific to the (NxCxHxW) case). I can make a pull request for this if you have a preferred way to deal with it

**Comment by theFool32** [comment]
Hi @iacolippo , could you give a successful example for it?

```
import foolbox
import numpy as np
import torch
from torchvision import models
from torchvision import transforms
import pdb

p_model = models.resnet50(pretrained=True).eval()
preprocessing = (np.array([[[[0.485]], [[0.456]], [[0.406]]]]), np.array([[[[0.229]], [[0.224]], [[0.225]]]]))
fmodel = foolbox.models.PyTorchModel(p_model, bounds=(0, 1), preprocessing=preprocessing, num_classes=1000, cuda=False)

image, label = foolbox.utils.imagenet_example()

# v_image = torch.from_numpy(np.transpose(image, (2, 0, 1))) / 255.0
# t = transforms.Normalize(mean=[0.485, 0.456, 0.406],
#                          std=[0.229, 0.224, 0.225])
# v_image = t(v_image)
# v_image = v_image.unsqueeze(0)
# out = p_model(v_image)
# print(out.max(1))

attack = foolbox.attacks.FGSM(fmodel)
adversarial = attack(np.transpose(image, (2, 0, 1))/255.0, label)
```
It seems not work due to
```
# foolbox/models/pytorch.py
# function predictions_and_gradient
# line 89
assert image.ndim == 3
```
since
```
# foolbox/model/base.py
# function predictions
# line 112
return np.squeeze(self.batch_predictions(image[np.newaxis]), axis=0)
```
make a image from (C, W, H) to (1, C, W, H)

Thanks again.

**Comment by jonasrauber** [comment]
Please have a look at the PyTorch example in the documentation: [https://foolbox.readthedocs.io/en/latest/user/examples.html](https://foolbox.readthedocs.io/en/latest/user/examples.html#creating-an-untargeted-adversarial-for-a-pytorch-model)

Hope that helps ;-)
