### ISSUE TITLE
ApproximateLBFGSAttack fails without specified target

### ISSUE THREAD

**Issue by lukas-schott** [bethgelab/foolbox#148]
ApproximateLBFGSAttack requires grad to find target class if not specified. 

Proposed fix: sooner fallback to random target (such a fall back is already implemented in LBFGSAttack if GradientAttack does not converge)

**Comment by jonasrauber** [comment]
Good point! I think the best way to do this is by overwriting the `__call__` method in the `ApproximateLBFGSAttack` class and setting the default value of `num_random_targets` to 1 and asserting that it is always greater than 0.

Could you make a pull request?
