### ISSUE TITLE
Non-class target

### ISSUE THREAD

**Issue by lucidyan** [bethgelab/foolbox#154]
Is a directional attack possible with the foolbox, if instead of the class label you have a numerical output of the penultimate layer and you need to minimize MSE between different examples?

I did not find any examples.

**Comment by jonasrauber** [comment]
That's currently not possible directly, but it should be relatively straight forward (for some attacks) to make the necessary modifications to get this to work. Let me know if you explore this route.

**Comment by lucidyan** [comment]
@jonasrauber 
You mean you're waiting for the pool-requests, right?

**Comment by jonasrauber** [comment]
Ah sorry, that was a mistake ;-)
I don't currently have time to work on this because I don't need it myself, but it would be an interesting addition to Foolbox.

**Comment by jonasrauber** [comment]
We don't have any plans to add this at the moment. While we would welcome contributions, I will close this issue for now as we don't expect this to happen anytime soon.
