### ISSUE TITLE
Feature Request: TargetClassProbability with uspecified target

### ISSUE THREAD

**Issue by maxdinech** [bethgelab/foolbox#156]
It cloud be really useful to let the attack determine a target on its own, to then increase its class probability above a given threshold.

**Comment by jonasrauber** [comment]
Have a look at [`OriginalClassProbability`](https://foolbox.readthedocs.io/en/latest/modules/criteria.html#foolbox.criteria.OriginalClassProbability). It can be used to reduce the probability of the original class. It's not the exact same thing, but might be useful in your case.

**Comment by maxdinech** [comment]
Thanks for the reply,

Unfortunately this method produces in some cases two labels with probabilities around 0.5 each or even three around 0.33, which is not great for creating strong adversarial examples.

The solution I went with is running an untargeted attack first to determine a target class, then use the `TargetClassProbability` criterion on that class.

**Comment by jonasrauber** [comment]
Updated and merged #151. Will be part of the next release (1.3.0).
