### ISSUE TITLE
Foolbox using adversarial attacks on images with a tensorflow slim pretrained model 

### ISSUE THREAD

**Issue by Arkadeep-sophoIITG** [bethgelab/foolbox#159]
I am using a tensorflow slim pretrained model for using adversarial attacks on an image and calculating the predictions. But I am stuck with this error for long. I don't understand why logits need to be cast to int64 and reshaped ?

Here's the code 

    graph = tf.Graph()
    image = np.asarray(Image.open('1.jpg'))
    data_tf = tf.convert_to_tensor(image,np.float32)
    data_tf = tf.reshape(data_tf,[1,299,299,3])
    print(data_tf.shape)
    with graph.as_default():

        global_step = slim.get_or_create_global_step()
        arg_scope = nets_factory.arg_scopes_map['inception_resnet_v2']()

        with slim.arg_scope(arg_scope):
            logits, end_points = nets_factory.networks_map['inception_resnet_v2'](
                data_tf,
                num_classes=2,
                is_training=False
            )

        variables_to_restore = slim.get_variables_to_restore()
        saver = tf.train.Saver(variables_to_restore)
        checkpoint_dir = '/local-scratch/arkadeep/ts09/final_model_pretrained_scratch'
        checkpoint_path = tf.train.latest_checkpoint(checkpoint_dir)
        with tf.Session() as sess:
            saver.restore(sess, checkpoint_path)
            model = foolbox.models.TensorFlowModel(data_tf, logits, (0, 255))
The error -

> Traceback (most recent call last):
  File "test.py", line 66, in <module>
    main()
  File "test.py", line 63, in main
    test()
  File "test.py", line 54, in test
    model = foolbox.models.TensorFlowModel(data_tf, logits, (0, 255))
  File "/home/ada77/.local/lib/python3.5/site-packages/foolbox/models/tensorflow.py", line 60, in __init__
    logits=self._logits[tf.newaxis])
  File "/rcg/software/Linux/Ubuntu/16.04/amd64/TOOLS/TENSORFLOW/1.8.0-CPU-PY352/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 2020, in sparse_softmax_cross_entropy_with_logits
    [labels, logits]):
  File "/rcg/software/Linux/Ubuntu/16.04/amd64/TOOLS/TENSORFLOW/1.8.0-CPU-PY352/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 5977, in __enter__
    g = _get_graph_from_inputs(self._values)
  File "/rcg/software/Linux/Ubuntu/16.04/amd64/TOOLS/TENSORFLOW/1.8.0-CPU-PY352/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 5637, in _get_graph_from_inputs
    _assert_same_graph(original_graph_element, graph_element)
  File "/rcg/software/Linux/Ubuntu/16.04/amd64/TOOLS/TENSORFLOW/1.8.0-CPU-PY352/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 5573, in _assert_same_graph
    original_item))
ValueError: Tensor("strided_slice:0", shape=(1, 2), dtype=int64) must be from the same graph as Tensor("strided_slice:0", shape=(1,), dtype=int64).

**Comment by jonasrauber** [comment]
Can you try replacing `with tf.Session() as sess:` with `with tf.Session().as_default() as sess:`

**Comment by Arkadeep-sophoIITG** [comment]
No that didnot help. I got it working , thanks anyway. Removing the graph.as_default() did the trick, because now both of the tensors belonged to the same graph.

Can you please give an example of applying an attack to a **batch** of images and performing  **batch_predictions with foolbox** methods like predicting the labels and the probability values corresponding to the logits [using [http://foolbox.readthedocs.io/en/latest/modules/utils.html#module-foolbox.utils](url)] 
of both the normal images and the adversarial images in  **Tensorflow.**

**Comment by jonasrauber** [comment]
To get predictions (e.g. logits) for a batch of images, you can use the `batch_predictions` method you mentioned. Adversarial attacks however always run on one input at a time, because many attacks internally need to evaluate the model on many inputs to create a single adversarial.
