### ISSUE TITLE
Typos in documentation

### ISSUE THREAD

**Issue by maikefer** [bethgelab/foolbox#167]
I found a few typos in the ReadTheDocs-documentation:

- Attacks > IterativeGradientSignAttack: Documentation of parameter 'steps' is missing but additionally 'max_epsilon' from GradientSignAttack is described: 
https://github.com/bethgelab/foolbox/blob/master/foolbox/attacks/gradientsign.py#L111
parameter 'epsilons' is probably inaccurate as well since there is no parameter max_epsilon ([...] between 0 and max_epsilon[..])

- Models: 'Backpropages', I guess you mean 'Backpropagates (6x) 
https://foolbox.readthedocs.io/en/latest/modules/models.html

**Comment by jonasrauber** [comment]
fixed in master by #168 and #169
