### ISSUE TITLE
Targeted FGSM attack? 

### ISSUE THREAD

**Issue by rogthlu** [bethgelab/foolbox#170]
I was trying to use targeted criteria with FGSM - it never seems to work... typically giving the "UserWarning: GradientSignAttack did not find an adversarial, maybe the model or the criterion is not supported by this attack." message.

It seems that FGSM with targeted criteria doesn't work in the current implementation. Is that correct?

Is there a reason this attack cannot be targeted? Would love to understand the difficulty there, if there is one!

**Comment by xerxes01** [comment]
Are you able to generate non targeted FGSM adversarial attacks? I get Assertion Error whenever I try to do it.

**Comment by jonasrauber** [comment]
FGSM is not really useful as targeted attack, the attack is just too weak.

**Comment by rogthlu** [comment]
OK.  In what sense do you mean "weak"?

Can you recommend which is the fastest targeted attack to run? (I'm using
KerasModel with inception v3 network) I've got targeted lbfgs and
untargeted fgsm working so far.

Many thanks.

**Comment by jonasrauber** [comment]
Well, FGSM only performs a single gradient step. To create an untargeted adversarial, that's often enough, but to create a targeted adversarial, a more powerful approach is often needed. You could try the [Basic Iterative Method](https://foolbox.readthedocs.io/en/latest/modules/attacks/gradient.html#foolbox.attacks.BasicIterativeMethod) (part of Foolbox v1.2.0) or it's [L1](https://foolbox.readthedocs.io/en/latest/modules/attacks/gradient.html#foolbox.attacks.L1BasicIterativeAttack) or [L2](https://foolbox.readthedocs.io/en/latest/modules/attacks/gradient.html#foolbox.attacks.L2BasicIterativeAttack) variants, depending on which norm you want to minimize.

**Comment by rogthlu** [comment]
That's excellent. After some more reading today I think I understand the attacks a bit better now. Thanks for your help. Great work on the Foolbox. Thanks.
