### ISSUE TITLE
Attacks Issue

### ISSUE THREAD

**Issue by xerxes01** [bethgelab/foolbox#172]
I am using a standard VGG16 and and trying to generate adversarial images using different attacks, however i am always greeted by this error : ValueError: Cannot feed value of shape (1, 1) for Tensor 'Placeholder_97:0', which has shape '(1,)'.
I don't understand what the problem is, as LBFGS attacks work perfectly fine, but all the others generate the above error.

**Comment by jonasrauber** [comment]
Well, the error basically states the problem, you have a shape mismatch. I am not sure why you even have a placeholder with shape `(1,)` when using VGG. When using TensorFlowModel, your shoud pass it to tensors, an images tensor (e.g. with shape (None, 224, 224, 3)) and a logits tensor (e.g. with shape (None, 1000)).

**Comment by xerxes01** [comment]
Yeah, I get that, however my custom VGG (for 100 classes) does the image classification and then I get no error of such type. I also tried generating adversarial on keras vgg16 pretrained on imagenet and got the same error. Where am I going wrong? Here's the code:

from keras.models import load_model
from keras.applications.vgg16 import VGG16
import foolbox
from foolbox.models import KerasModel
from foolbox.attacks import LBFGSAttack
from foolbox.criteria import TargetClass
import numpy as np
import foolbox
keras.backend.set_learning_phase(0)

model=VGG16(weights='imagenet')
fmodel = foolbox.models.KerasModel(model, bounds=(0, 255))

from PIL import Image
img = Image.open('/home/shikhar/Downloads/suit.jpeg')
img = img.resize((224,224))
img = np.asarray(img)
img = img[:, :, :3]

lab=model.predict(np.expand_dims(img, axis=0))
label=np.argmax(lab,axis=1)

from foolbox.criteria import Misclassification, TargetClass
attack = foolbox.attacks.FGSM(model=fmodel,criterion=TargetClass(567))
adversarial = attack(img, label,unpack=False)

The error that I get is :
Cannot feed value of shape (1, 1) for Tensor 'Placeholder_32:0', which has shape '(1,)'

**Comment by jonasrauber** [comment]
I cannot reproduce this problem. Works totally fine (running your code does not produce the shape error you reported):
https://gist.github.com/jonasrauber/fb01a418bb4457e2d05b26ed73875be5

Nevertheless, your code contains some mistakes: you are not doing the correct preprocessing that is expected by Keras. Please have a look at the Jupyter notebook and the Foolbox Readme.

**Comment by xerxes01** [comment]
Thank you so much for the detailed ipynb! Solved my problem

**Comment by jonasrauber** [comment]
Could you let us know what the issue was?
