### ISSUE TITLE
Add Virtual Adversarial Attack

### ISSUE THREAD

**Issue by wielandbrendel** [bethgelab/foolbox#186]
This attack was originally proposed by Miyato et al. (2016) and was used for virtual adversarial training. Paper link: https://arxiv.org/abs/1507.00677

A reference implementation is available in the IBM Toolbox:

https://github.com/IBM/adversarial-robustness-toolbox/blob/master/art/attacks/virtual_adversarial.py

**Comment by jonasrauber** [comment]
see #347
