### ISSUE TITLE
Setting GPU for pytorch model

### ISSUE THREAD

**Issue by renebidart** [bethgelab/foolbox#195]
In pytorch v.4 you can select the GPU the model is using by using .to(device), where device will be something like cuda:0. Is there a way to do this using foolbox? Or should we change the foolbox pytorch model class to allow this?

Thanks,
Rene

**Comment by wielandbrendel** [comment]
This requires a small change in the API of the Pytorch Model (instead of cuda-argument we could use the device argument which defaults to cuda:0 if available). @renebidart Would you mind doing a PR for this feature?

**Comment by renebidart** [comment]
No problem @wielandbrendel

**Comment by jonasrauber** [comment]
work in progress: #196

**Comment by jonasrauber** [comment]
support added in #206
