### ISSUE TITLE
Gradient close/equal to 0?

### ISSUE THREAD

**Issue by linzhiqiu** [bethgelab/foolbox#198]
I was attacking my own PyTorch model ( for image binary classification ) using `L2BasicIterativeAttack`, `foolbox.criteria.TargetClassProbability`, and `distance=foolbox.distances.MSE` - everything wrapped in `foolbox.adversarial.Adversarial`.

However, the I checked the gradient I get when doing the backward(), and it turned out they are all 0 or very close to 0. This thus causes some NaN errors later in the code.

Any insights into this issue?

**Comment by linzhiqiu** [comment]
I think you are right. `fmodel.gradient(image, label)` returns a zero array. Now I am confused.

I am using a Resnet101 model, yet I changed the output of the last fc layer to 2. Also I changed the last Average Pooling layer to Adaptive Pooling (or Global Pooling) in order to handle variable size images. I don't think this makes my model non-differentiable though :-(

**Comment by linzhiqiu** [comment]
I think this has to do with the way PyTorch stores its gradient. Many people said PyTorch do not always keep the gradient, and the best way to get gradient is through `hook` (see there)[

**Comment by jonasrauber** [comment]
Not sure I get this explanation because it works well for us.
