### ISSUE TITLE
What does the attack methods do if there are no adversarial found?

### ISSUE THREAD

**Issue by xiaomi1213** [bethgelab/foolbox#200]
-------------------------generating adversarial examples-----------------------------
/home/dell/anaconda3/lib/python3.6/site-packages/foolbox/attacks/base.py:103: UserWarning: **GradientSignAttack did not find an adversarial, maybe the model or the criterion is not supported by this attack.**
(9827,)

-------------------------evaluate cnn with adv-----------------------------
Traceback (most recent call last):
  File "/home/junhang/Projects/Scripts/src/pycharm/vae_adversarial_test.py", line 77, in <module>
    test_output = cnn_model(torch.from_numpy(cnn_adv_xs_arr).cuda())
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: double, float, float16, int64, int32, and uint8.

**Does the attack generate 'None' type adversarial examples so that 'from_numpy()' method can not deal with 'None' type?**

**Comment by wielandbrendel** [comment]
Indeed, if no adversarial is found then the attack returns None.
