### ISSUE TITLE
Implement Spatial Grid Attack

### ISSUE THREAD

**Issue by wielandbrendel** [bethgelab/foolbox#201]
We should implement the spatial grid attack from "A Rotation and a Translation Suffice: Fooling CNNs with Simple Transformations", Engstrom et al. 2018. https://arxiv.org/pdf/1712.02779.pdf

**Comment by jonasrauber** [comment]
Is that what you did?
Also see #269

**Comment by wielandbrendel** [comment]
Yes :)
