### ISSUE TITLE
Support early stopping at threshold

### ISSUE THREAD

**Issue by wielandbrendel** [bethgelab/foolbox#203]
We should think about a general early stopping argument that says: as soon as you reach a certain threshold do not optimise further. Many people use this and it's easy to implement as part of our adversarial object which anyway tracks the smallest adversarial.

What do you think?

**Comment by jonasrauber** [comment]
I agree; it can be a useful thing; for many attacks, knowing about this threshold would however make sense because it could make them more efficient

**Comment by jonasrauber** [comment]
https://github.com/google/unrestricted-adversarial-examples/issues/22

**Comment by jonasrauber** [comment]
this is now supported in Foolbox 1.5.0
