### ISSUE TITLE
Is it possible to do batch attack using foolbox? Or does it only support per image attack?

### ISSUE THREAD

**Issue by yxchng** [bethgelab/foolbox#208]
If it does support, how should I do it? Otherwise I have to use a loop to generate the attacks which is very slow and inefficient.

**Comment by wielandbrendel** [comment]
Batch-processing is on our todo-list but currently not implemented. The reasoning was that time is usually not a limiting factor for adversarial attacks (aside maybe from the Boundary attack which does use batching internally) and so we opted for simplicity. But I agree that this would be a nice thing to have.

**Comment by jonasrauber** [comment]
It’s on our agenda, but many attacks are fast anyway (so it’s fine to run them sequentially) and some slow ones (e.g. Boundary Attack) do perform batch predictions already to find a single adversarial (so there is not much to win by calculating adversarials for a whole batch).

Just use a loop (use tqdm for nice progress indicators) or parellize across GPUs (something we cannot easily abstract away anyway). It works well for us and we have done many large scale evaluations.

**Comment by akash-joshi** [comment]
Yeah, this works ! Btw, how do we evaluate this new array of attacked images by our original model.
As in : `score = model.evaluate(adversarial_array, y_test, verbose=0)`

**Comment by jonasrauber** [comment]
@akash-joshi not sure I understand your question… maybe `np.argmax(fmodel.batch_predictions(adversarial_array), axis=1) == y_test` is what you are looking for… but that's not really necessary, because whenever a Foolbox attack returns an array, it's guaranteed to be an adversarial (otherwise it returns None)

**Comment by akash-joshi** [comment]
@jonasrauber I have my Foolbox image array generated by this : 
```adversarial = []
for i in tqdm(range(5000)) :
  image = x_test[i]
  label = y_classes[i]
  advers = attack(image,label)
  adversarial.append(advers)```

I want to compare its accuracy in my model with the original test set.

```score = model.evaluate(x_test, y_test, verbose=0)
adver_score = model.evaluate(adversarial,y_test,verbose=0)```

However, I'm having shape issues on the adver_score line as adversarial is created as a list. Converting it to array using numpy.array() also doesn't help. Have you ever written such a code ?

Colab : https://colab.research.google.com/drive/1EsFegH4ik_2FZ54vIUkpAeYj6J_s7MUO#scrollTo=VZtqBqFFy62R

**Comment by jonasrauber** [comment]
PR  #295 contains a prototype! Please give it a try.

**Comment by jonasrauber** [comment]
Batch-support is finally here. Please try our newest beta version: Foolbox 2.0.0b0.
