### ISSUE TITLE
Why do you multiply the gradient of GradientAttacks with (max_-min_)?

### ISSUE THREAD

**Issue by yxchng** [bethgelab/foolbox#209]
I notice that you multiply the gradient with `(max_-min_)`, i.e. for GradientSignAttack,
`gradient = np.sign(gradient) * (max_ - min_)` and for GradientAttack, `gradient = gradient / (gradient_norm + 1e-8) * (max_ - min_)`, which for bounds (0,255), it is 255.

Is there any reason for doing this? 

I do see some people do this when they want to transform it back to the space of (0,255) when they are using bounds (0-1) to train their model. However, if I am already using (0-255), it doesn't seem right, does it?

**Comment by wielandbrendel** [comment]
This scaling is meant to make epsilon independent of the bounds. E.g. an epsilon = 0.1 in the GradientSignAttack means that you perturb the image by 10% relative to the min - max range (which could e.g. from 0 to 1 or 255).

**Comment by jonasrauber** [comment]
added to FAQ: https://foolbox.readthedocs.io/en/latest/user/faq.html
