### ISSUE TITLE
About Target Attack Methods

### ISSUE THREAD

**Issue by persistz** [bethgelab/foolbox#211]
I noticed that almost every attack class have the input para "criterion=<foolbox.criteria.Misclassification object>", is that meaning all of them can be used for target attacking?
Or just the L-BGFS, which has the parameter "num_random_targets=0", can be used for target attack?

When I used FGSM for target attack, usually got an output: GradientSignAttack did not find an adversarial, maybe the model or the criterion is not supported by this attack.

**Comment by jonasrauber** [comment]
Depends, some attacks are more likely to achieve targeted misclassification, others less. FGSM or noise attacks are usually not powerful enough to be targeted, but L-BFGS, the BoundaryAttack or iterative gradient attacks usually do find targeted adversarials.

**Comment by jonasrauber** [comment]
In any case, every attack has a `criterion` parameter, because there can be many more criteria, not just targeted and untargeted but also probability thresholds, etc.

**Comment by jonasrauber** [comment]
@persistz please close if this answers your question

**Comment by persistz** [comment]
Thanks a lot, i just closed it.

**Comment by xinhongri** [comment]
FGSM is not really useful as targeted attack, the attack is just too weak. You should use more powerful attacks when you want to create targeted adversarials.
