### ISSUE TITLE
GPU is not used while attacking

### ISSUE THREAD

**Issue by mjasim** [bethgelab/foolbox#229]
Hi.

I am using ResNet50 with keras based on the example code. FGSM works fine but LBFGS is unusually slow. Even after setting maxiter = 5, it takes more than a minute to produce the adversarial example. Same experience with PGD.

I have a GPU (1050 Ti) but while I was running the code I checked the performance and the GPU was not being used at all. Could you please suggest how can I trigger the GPU? Or should it have been triggered by the API?

```
import foolbox
import keras
import numpy as np
from keras.applications.resnet50 import ResNet50
import pandas as pd
from PIL import Image, ImageFilter
import matplotlib.pyplot as plt

keras.backend.set_learning_phase(0)
kmodel = ResNet50(weights='imagenet')
preprocessing = (np.array([104, 116, 123]), 1)
fmodel = foolbox.models.KerasModel(kmodel, bounds=(0, 255), preprocessing=preprocessing)

image, label = foolbox.utils.imagenet_example()

attack = foolbox.attacks.LBFGSAttack(fmodel)
adversarial = attack(image[:, :, ::-1], label, maxiter = 5)

plt.subplot(1, 3, 1)
plt.imshow(image)
plt.subplot(1, 3, 2)
plt.imshow(adversarial)
plt.subplot(1, 3, 3)
plt.imshow(adversarial - image)
```

**Comment by jonasrauber** [comment]
I recommend you check whether the keras model does use the GPU in your case, ignoring any Foolbox code. I would guess that this problem has nothing to do with Foolbox

**Comment by mjasim** [comment]
You are correct. My mistake. I assumed since tensorflow backend was used keras model used GPU. Thanks for the clarification.
