### ISSUE TITLE
Return the failed adversarial sample

### ISSUE THREAD

**Issue by iliaishacked** [bethgelab/foolbox#230]
Hi,

In order to evaluate an adversarial sample detection mechanism, I was looking for an option to get the failed adversarial sample for a given attack. 

I tried redefining my own Criterion to always return True, that however, cause attacks to misbehave. 

Is there some option I am missing? Like some option to pass the kwargs into the "is_adversarial" method?

**Comment by wielandbrendel** [comment]
What do you mean by "failed adversarial sample"? Do you mean that you'd like to track all perturbed images generated by an attack irrespective of whether it was adversarial or not?

**Comment by jonasrauber** [comment]
You could just track all model evaluations by overwriting the corresponding methods of the Model class. At that point you have access to the image and to the prediction.

**Comment by iliaishacked** [comment]
To whoever who wants to solve a similar problem, I ended up just cacheing the samples in the forward of the model I provided to foolbox.

**Comment by xerxes01** [comment]
@iliaishacked Could you please elaborate on the solution? I too am trying to evaluate my model robustness on failed adversarial samples.
