### ISSUE TITLE
Evaluate Model Robustness

### ISSUE THREAD

**Issue by xerxes01** [bethgelab/foolbox#235]
Is there any way of evaluating my model robustness on images generated using RandomPGD attack under certain hyper parameters (epsilon value) like they did in ALP (https://github.com/tensorflow/models/tree/master/research/adversarial_logit_pairing)? 
Foolbox does not return an image unless an adversarial is generated, whereas I want to test the model accuracy on those perturbed images.

**Comment by jonasrauber** [comment]
The attacks take an argument named `threshold` that let's you specify that you are only interested in whether there are perturbations smaller than that threshold or not: https://foolbox.readthedocs.io/en/stable/modules/adversarial.html#foolbox.adversarial.Adversarial
