### ISSUE TITLE
indices = np.argsort(scores)[:t] should be -t

### ISSUE THREAD

**Issue by duoergun0729** [bethgelab/foolbox#237]
indices = np.argsort(scores)[:t]  means the least ones ,but local search wants the biggest ones

**Comment by wielandbrendel** [comment]
Why would localsearch search the biggest scores (= probabilities)? It searches perturbations that reduce the probabilities of the source class as much as possible, so this line looks correct to me. Let me know if that makes sense to you.

**Comment by wielandbrendel** [comment]
What happens when you change to the order? Does attack success rate increase?

**Comment by duoergun0729** [comment]
success rate increase and run faster  ,you can try it :)

**Comment by wielandbrendel** [comment]
@jonasrauber Can you take a look at this?

**Comment by jonasrauber** [comment]
Thanks a lot! I finally looked into this and this was indeed a bug in our implementation. Will be fixed in the next release.
