### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by gobbedy** [bethgelab/foolbox#239]
Can I just say that this is the coolest project ever? *Reads papers, wishes all the attacks were implemented for him in pytorch. Finds out it is and cries.*

That's all. You can close this issue whenever you feel or leave it open :)

**Comment by wielandbrendel** [comment]
Cool, thanks for the encouragement @gobbedy . You'll love a couple of features that we are currently implementing. We just released one feature: the foolbox model zoo, which lets you load published defences with a single line of code.

**Comment by gobbedy** [comment]
That looks amazing. I just can't get over how state of the art research is so easily accessed in a few lines of python.

**Comment by wielandbrendel** [comment]
Great you like it!
