### ISSUE TITLE
Problem with creating attacks/ adversarial instances using pytorch (in example code)

### ISSUE THREAD

**Issue by filbart** [bethgelab/foolbox#241]
Hello,
I've run into a similiar issue as #194 while trying to run example code. I am recieving a following error while creating the attack ( adversarial = attack(image, label) )

RuntimeError: Expected object of type torch.LongTensor but found type torch.IntTensor for argument #2 'target'

I've checked and updated versions of foolbox, torch, torchvision, numpy and scipy.
Also tried rewriting the example slightly (code below), still getting the same error.

``` python
import foolbox
import torch
import torchvision
import torchvision.models as models
import numpy as np

device = torch.device('cpu')

resnet18 = models.resnet18(pretrained=True).to(device).eval()

mean = np.array([0.485, 0.456, 0.406]).reshape((3, 1, 1))
std = np.array([0.229, 0.224, 0.225]).reshape((3, 1, 1))
fmodel = foolbox.models.PyTorchModel(
    resnet18, bounds=(0, 1), num_classes=1000, preprocessing=(mean, std), device=device)

image, label = foolbox.utils.imagenet_example(data_format='channels_first')
image = image / 255.  # because our model expects values in [0, 1]

print('label', label)
print('predicted class', np.argmax(fmodel.predictions(image)))

attack = foolbox.attacks.FGSM(fmodel)
adversarial = attack(image, label)

print('adversarial class', np.argmax(fmodel.predictions(adversarial)))
```

**Comment by samuelemarro** [comment]
Converting standard types to Torch tensors is a bit messy and often leads to bugs such as this one.  As a workaround, replace `attack(image, label)` with `attack(image, np.array(label, dtype=np.int64))`.

**Comment by filbart** [comment]
Works like a charm, thanks!

**Comment by wielandbrendel** [comment]
Thanks for reporting and thanks for the work-around! I fixed this problem in master.
