### ISSUE TITLE
ValueError: attempt to get argmin of an empty sequence

### ISSUE THREAD

**Issue by wjadvos** [bethgelab/foolbox#249]
When I do an attack with the foolbox, for 6 pictures everything works fine, but the i get the following error:

> File "/home/wouter/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
>     return getattr(obj, method)(*args, **kwds)
> AttributeError: 'list' object has no attribute 'argmin'
> 
> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
>   File "haveassertionError.py", line 154, in <module>
>     truelabels,falselabels=distancePerturb(val)
>   File "haveassertionError.py", line 114, in distancePerturb
>     adverserial=attack(image,label=falselabel)
>   File "/home/wouter/anaconda3/lib/python3.6/site-packages/foolbox/attacks/base.py", line 137, in wrapper
>     _ = call_fn(self, a, label=None, unpack=None, **kwargs)
>   File "/home/wouter/anaconda3/lib/python3.6/site-packages/foolbox/attacks/deepfool.py", line 144, in __call__
>     optimal = np.argmin(distances)
>   File "/home/wouter/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1068, in argmin
>     return _wrapfunc(a, 'argmin', axis=axis, out=out)
>   File "/home/wouter/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 62, in _wrapfunc
>     return _wrapit(obj, method, *args, **kwds)
>   File "/home/wouter/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 42, in _wrapit
>     result = getattr(asarray(obj), method)(*args, **kwds)
> ValueError: attempt to get argmin of an empty sequence
> 

Used code: (image represents a loaded image)
``model=KerasModel(model2,bounds=(0,1))	
distance=foolbox.distances.MeanSquaredDistance	
attack=foolbox.attacks.DeepFoolAttack(fmodel, distance=distance)
adverserial=attack(image,label=truelabel)``

This issue is raised already, but quite old, so that's why I post it here.
From what it says it seems that no adverserial perturbation has been found, but I am not sure. That's why I ask it here..

**Comment by wielandbrendel** [comment]
Are you sure that false label is a valid integer and not, e.g., None? Is there a minimum working example that you could post?

**Comment by jakubLangr** [comment]
Hi, +1! Just got this error as well specifically with the DeepFoolAttack—I have been trying all of them to see how they differ. 

Can confirm that the label is a valid integer. Will post a valid example after this batch finishes, but pretty sure if you just replace the `LBFGSAttack` by `DeepFool` in #261 it will reproduce.

Did you solve this by any chance @wjadvos ?

**Comment by jakubLangr** [comment]
Hi, yes as I said this would work:

```
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import keras
import cv2
import foolbox
from PIL import Image
from foolbox.criteria import Misclassification, TargetClassProbability, \
                            ConfidentMisclassification
from keras.preprocessing import image as img
from keras.applications.resnet50 import preprocess_input, decode_predictions
from keras.applications.resnet50 import ResNet50
import numpy as np
import pandas as pd
%matplotlib inline

# instantiate model
keras.backend.set_learning_phase(0)
kmodel = ResNet50(weights='imagenet')
preprocessing = (np.array([104, 116, 123]), 1)
fmodel = foolbox.models.KerasModel(kmodel, bounds=(0, 255), preprocessing=preprocessing)

mu_list = range(50, 200, 10)
sigma_list = range(10, 100, 2)
storage_df = pd.DataFrame()

for mu, sigma in zip(mu_list, sigma_list):
    rand_noise = np.random.normal(loc=mu, scale=sigma, size=(224,224, 3))
    rand_noise = np.clip(rand_noise, 0, 255.)
    noise_preds = kmodel.predict(np.expand_dims(rand_noise, axis=0))
    predictions = decode_predictions(noise_preds, top=20)[0]
    new_df = pd.DataFrame(predictions, columns=['id','class','prediction'])
    new_df['sigma'] = sigma
    new_df['mu'] = mu
    storage_df = pd.concat([new_df, storage_df])
   
sum_pred = []
rand_noise = np.random.normal(loc=mu, scale=sigma, size=(224,224, 3))
rand_noise = np.clip(rand_noise, 0, 255.)
first_pred = kmodel.predict(np.expand_dims(rand_noise, axis=0))
label = np.argmax(first_pred)
attack = foolbox.attacks.DeepFoolAttack(fmodel, 
                                     # distance=foolbox.distances.Linfinity,
                                     criterion=ConfidentMisclassification(.75))
adversarial = attack(rand_noise[:, :, ::-1], label)
# adversarial = adversarial.image
# import ipdb; ipdb.set_trace()
print(adversarial)
noise_preds = kmodel.predict(np.expand_dims(adversarial, axis=0))
prediction, num = decode_predictions(noise_preds, top=20)[0][0][1:3]
num = round(num * 100, 2)
print(prediction, num)
print(decode_predictions(noise_preds, top=20)[0][0])
```

**Comment by jakubLangr** [comment]
More than happy to collaborate on this one. I have been stepping through the debugger meticulously and happy to share insights—via a Skype call or anything that would work.

**Comment by jonasrauber** [comment]
The problem is that there are no `residual_labels` left for DeepFool to work on. Roughly speaking, DeepFool is only designed for `Misclassification`, not `ConfidentMisclassification` (with `subsample=False` DeepFool might work longer, but even then this case can happen, if the original class is the least likely one but still no other class is above 75%) . We should certainly improve the error message here.
