### ISSUE TITLE
Problems with testing the ResNet50 example

### ISSUE THREAD

**Issue by roughentomologyx** [bethgelab/foolbox#251]
Hey my friends,
i tried to test the given ResNet50 example from the github front page. I'm able to get a picture (Original, Adversarial, Difference) that looks just the same as the picture on the example on the front page of github with the given instructions. But then i tried to save the adversarial picture and run it against the keras RESNet50 ImageNet classifier given at  https://keras.io/applications/#classify-imagenet-classes-with-resnet50.
But it just always returns some cat classes with confidence <0.30. So i guess i'm making a mistake in saving the picture. Maybe you can help me.
Here is how i save:
```python
fig = plt.figure(figsize=(2.92, 2.92)) #244x244 px image, see foolbox.utils.imagenet_example
ax = fig.add_subplot(1, 1, 1) #needed to get rid of pyplot padding
plt.imshow(adversarial[:, :, ::-1] / 255)#imshow of adversarial(second) picture
plt.xticks([])#get rid of scale
plt.yticks([])#get rid of scale
ax.axes.get_xaxis().set_visible(False)#get rid of axis
ax.axes.get_yaxis().set_visible(False)#get rid of axis
ax.set_frame_on(False)#get rid of frame
plt.savefig('testkeras.png', bbox_inches = 'tight', pad_inches = 0)# get rid of padding
plt.close(fig)
```

Thank you in advance.

**Comment by wielandbrendel** [comment]
That can happen because the perturbation is in float32 but you are saving the image in int8, so you are loosing much of the perturbations. Save it as a numpy array, not an image.
