### ISSUE TITLE
Return image for each gradient step

### ISSUE THREAD

**Issue by xerxes01** [bethgelab/foolbox#259]
I need to evaluate my model's defence on the perturbed images obtained by RPGD attack, however foolbox does not return the image in case the attack fails. Which specific module should be edited in order to return the failed adversarial sample?

**Comment by wielandbrendel** [comment]
I don't think you need the failed adversarial sample - that's just some image which is not adversarial, so I don't see why you would be interested in it. Are you generating adversarials on the undefended model and test on the defended one?

**Comment by wielandbrendel** [comment]
Right - that's just the inverse attack success rate.

**Comment by xerxes01** [comment]
Oh Okay! Also is it the same for measuring defence on targeted attacks as well?

**Comment by wielandbrendel** [comment]
Sure.

**Comment by wielandbrendel** [comment]
Well, you only perform a targeted attack if you define an adversarial as a perturbed image classified as the target class. Everything else is not adversarial and so you keep computing the adversarial success as before.

**Comment by xerxes01** [comment]
Got it! Thanks!
