### ISSUE TITLE
Cannot install on Windows 10

### ISSUE THREAD

**Issue by lshhsl** [bethgelab/foolbox#26]
Hello, I meet a problem when I install the package on Win10.
"running install
running bdist_egg
running egg_info
creating UNKNOWN.egg-info
writing UNKNOWN.egg-info\PKG-INFO
writing top-level names to UNKNOWN.egg-info\top_level.txt
writing dependency_links to UNKNOWN.egg-info\dependency_links.txt
writing manifest file 'UNKNOWN.egg-info\SOURCES.txt'
reading manifest file 'UNKNOWN.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'UNKNOWN.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
warning: install_lib: 'build\lib' does not exist -- no Python modules to install

creating build
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\EGG-INFO
copying UNKNOWN.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying UNKNOWN.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying UNKNOWN.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying UNKNOWN.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist\UNKNOWN-0.6.0-py3.5.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing UNKNOWN-0.6.0-py3.5.egg
Removing c:\python35\lib\site-packages\UNKNOWN-0.6.0-py3.5.egg
Copying UNKNOWN-0.6.0-py3.5.egg to c:\python35\lib\site-packages
UNKNOWN 0.6.0 is already the active version in easy-install.pth

Installed c:\python35\lib\site-packages\unknown-0.6.0-py3.5.egg
Processing dependencies for UNKNOWN==0.6.0
Finished processing dependencies for UNKNOWN==0.6.0"

**Comment by wielandbrendel** [comment]
Which command did you execute (pip install foolbox?) and what pip version are you using?

**Comment by wielandbrendel** [comment]
Glad you solved it! @jonasrauber : do you have an idea why this would be needed (name is part of the setup.cfg)?

**Comment by jonasrauber** [comment]
My guess is that the version of setuptools is too old and doesn't support the cfg-file based configuration. If so, it might be worth switching to the old way of specifying the setup parameters. 

@lshhsl Could you let me know which setuptools version you are using? `pip list` should show all installed packages and their version number. 

Thanks for reporting the issue and the solution.

**Comment by wielandbrendel** [comment]
So lets add a minimum setuptools version to the install requirements, right? @lshhsl could you report your setuptools version?

**Comment by lshhsl** [comment]
My setuptools version is 20.7.0. And I find that It still cannot work if only change the setup.py as before. I copy the foolbox/foolbox directory to the python/lib/sitepackages/, and it works.

**Comment by jonasrauber** [comment]
Hi @lshhsl, can you try again. Version 0.7.0 should fix this problem.

**Comment by jonasrauber** [comment]
Closing this because the issue seems to be resolved.
