### ISSUE TITLE
InvalidArgumentError: The first dimension of paddings must be the rank of inputs

### ISSUE THREAD

**Issue by jakubLangr** [bethgelab/foolbox#261]
I have been fighting with this issue since Christmas and now I was able to come back to it and I think I am not insane.

Here's a Min Reproducible Example:

```
import foolbox
from foolbox.models import KerasModel
from foolbox.attacks import LBFGSAttack
from foolbox.criteria import TargetClassProbability
import numpy as np
import keras
from keras.applications.resnet50 import ResNet50
from keras.applications.resnet50 import preprocess_input
from keras.applications.resnet50 import decode_predictions

keras.backend.set_learning_phase(0)
kmodel = ResNet50(weights='imagenet')
preprocessing = (np.array([104, 116, 123]), 1)
fmodel = KerasModel(kmodel, bounds=(0, 255), preprocessing=preprocessing)

import cv2 
image = cv2.imread("example.png") # same example as in the library except loaded with opencv 
# to get easier access to numpy arrays
image = cv2.resize(image, (224,224))
image = image[:,:,::-1]
# run the attack
attack = LBFGSAttack(model=fmodel, criterion=TargetClassProbability(781, p=.5))
adversarial = attack(image[:, :, ::-1], label)
# show results
if len(adversarial.shape)!=4:
    adversarial = np.expand_dims(adversarial, axis=0)
print(np.argmax(fmodel.predictions(adversarial[0])))
print(foolbox.utils.softmax(fmodel.predictions(adversarial))[781])

preds = kmodel.predict(preprocess_input(adversarial))
print("Top 5 predictions (adversarial: ", decode_predictions(preds, top=5))
```
I get the error message above: `InvalidArgumentError: The first dimension of paddings must be the rank of inputs` Further information:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: The first dimension of paddings must be the rank of inputs[4,2] [1,1,224,224,3]
     [[{{node conv1_pad/Pad}} = Pad[T=DT_FLOAT, Tpaddings=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_input_1_0_0, conv1_pad/Pad/paddings)]]
```
The error occurs on this line `print(foolbox.utils.softmax(fmodel.predictions(adversarial))[781])`. 

Any ideas why? It is equally not happy with adversarial of shape `(224, 224, 3)` as well as `(1,224,224,3)`.

**Comment by jonasrauber** [comment]
Just change `adversarial` to `adversarial[0]` like you do in the line above. Then the code runs as expected. Or just remove the `expand_dims`, then you also don't need the `[0]` ...

**Comment by aniskoubaa** [comment]
Is there any solution for this?
I also tried the same input with and without expand_dims and it did not work. 
I get the error 
responseJSON: {error: "The first dimension of paddings must be the rank o…[4,2] [150528]

**Comment by jonasrauber** [comment]
I posted the solution above. With that change the code did run as expected.
@aniskoubaa I guess your code and issue is different. Also, I recommend updating to Foolbox 3 if you haven't done yet.
