### ISSUE TITLE
Informations about usage of boundary attack

### ISSUE THREAD

**Issue by martinmatak** [bethgelab/foolbox#266]
Hi, 

In the paper for the boundary attack [1], I found a reference to this framework.

What I find particularly interesting in the paper and would like to replicate is how does an original image change towards adversarial sample with number of queries in the (targeted version of the) attack. I like how you presented it in the paper, but I can't see how to replicate that.

Not sure actually even when and how my model is queried. 

- How is API of the given model used, i.e. can it be replaced with some other API? (e.g. Clarifai)
- Is the number of steps (those that are printed in std out when `verbose=True`) equal to number of queries of the blackbox target? 
- Is it possible to save image after every _n_ queries? 
- Is it possible to save image as soon as it is classified as a target label? 

[1] https://arxiv.org/abs/1712.04248

**Comment by wielandbrendel** [comment]
Please check #253 for information of how to use Foolbox with external predictors (like a Web API) for use with the Boundary attack.
