### ISSUE TITLE
Some issue with Sequential Keras Model when using non-Image type data

### ISSUE THREAD

**Issue by shreyansh26** [bethgelab/foolbox#267]
I am using Foolbox to generate adversarial examples for non-image type data. The data is entirely numeric, scaled between 0 and 1. I have trained a Keras Model which I want to attack.
The model was generated using this - 
```
model = Sequential()
model.add(Dense(256, activation='relu', input_shape=(X_train_scaled.shape[1], )))
model.add(Dropout(0.2))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(FLAGS.nb_classes, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
```

However, when I run the following command - 
`fmodel = foolbox.models.KerasModel(model, bounds=(0, 1))`, I get the following error -
```
AttributeError                            Traceback (most recent call last)
<ipython-input-32-6eea7359842d> in <module>()
----> 1 fmodel = foolbox.models.KerasModel(model, bounds=(0, 1))

/usr/local/lib/python3.5/dist-packages/foolbox/models/keras.py in __init__(self, model, bounds, channel_axis, preprocessing, predicts)
     51         assert predicts in ['probabilities', 'logits']
     52 
---> 53         images_input = model.input
     54         label_input = K.placeholder(shape=(1,))
     55 

/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py in input(self)
    923         if len(self.inbound_nodes) > 1:
    924             raise AttributeError('Layer ' + self.name +
--> 925                                  ' has multiple inbound nodes, '
    926                                  'hence the notion of "layer input" '
    927                                  'is ill-defined. '

AttributeError: Layer sequential_1 has multiple inbound nodes, hence the notion of "layer input" is ill-defined. Use `get_input_at(node_index)` instead.
```

Please suggest a solution to resolve this?

**Comment by jonasrauber** [comment]
Well, have you checked why your model has more than one input and can you change it to have one.

**Comment by shreyansh26** [comment]
The data that I have has 125,973 rows and 122 columns (features) in the training set. So the is why the `input_shape` has been set to `(122, )`. If that is the issue here, how can I make it a single input model?

**Comment by jonasrauber** [comment]
No, that's not the issue. But your model apparently has two (or more) input tensors. Please investigate why. As the error message suggests, you could use `get_input_at` to check what the different inputs are. Maybe that helps with figuring out why there is more than one input tensor.

**Comment by lynn901213** [comment]
@shreyansh26 using Sequential() in Keras will result in 2 inbounding nodes and 2 outbounding nodes as it's a sequential wrapping on model layers from my understanding. Quick fix to this is to modify the keras.py file from foolbox package, and change images_input = model.input -> images_input = model.inputs[-1], similar to the output change predictions = model.output -> predictions = model.outputs[-1].

**Comment by jonasrauber** [comment]
Just tried to reproduce this, but the above model has only one input for me and the code works fine.
