### ISSUE TITLE
Usage of targeted boundary attack

### ISSUE THREAD

**Issue by martinmatak** [bethgelab/foolbox#270]
I am confused how does targeted version of the boundary attack work.
This is what I understood from the paper.

Assume there are two images and their respective labels*: imageDog (labelDog) and imageCat (labelCat).

Goal of adversary is to make imageDog look as imageCat to a human, but stay classified as imageDog.

But I am confused with the API of the attack. 
In the aforementioned scenario, would this be an appropriate code: 

```
fmodel = foolbox.models.KerasModel(prep_bbox(), bounds=(0, 255))
attack = foolbox.attacks.BoundaryAttack(fmodel)
adversarial = attack(input_or_adv=imageCat, label=labelCat, starting_point=imageDog)
```
?

After 5k steps, I do get an adversarial sample back and it is very similar to imageCat, but it is not classified as imageDog anymore.

Images are 224x224x3 images. Last time I got the message "Boundary too linear" was after Step 669. Last time I got the message "Boundary too non-linear" was after step 4919.

What am I doing wrong? 

*I actually have 100 classes that represent how old a person in the image is

**Comment by wielandbrendel** [comment]
You have to let the attack know that you are running a targeted attack. To do this, add `criterion=foolbox.criteria.TargetClass(22)` when you instantiate the BoundaryAttack.

**Comment by martinmatak** [comment]
But why is then `label` argument needed in `attack` call when the goal is to make `starting_point` image only look like `input_or_adv` image, but stay labeled as targeted?

**Comment by wielandbrendel** [comment]
The label argument is not used in this case (I think you can set it to None).

**Comment by martinmatak** [comment]
I get an error if I don't pass it. I tried now to pass a dummy variable and it works. This seems to me as a new API could come soon? :)

**Comment by wielandbrendel** [comment]
I agree the API is not ideal. We are open to suggestions! :)

**Comment by kanak000** [comment]
> fmodel = foolbox.models.KerasModel(prep_bbox(), bounds=(0, 255))
> attack = foolbox.attacks.BoundaryAttack(fmodel)
> adversarial = attack(input_or_adv=imageCat, label=labelCat, starting_point=imageDog)

hey, can you please share your code. I am having a bit of difficulty in running this code
