### ISSUE TITLE
AttributeError: 'Sequential' object has no attribute 'bounds'

### ISSUE THREAD

**Issue by MalharJ** [bethgelab/foolbox#273]
I first trained a custom neural network on CIFAR-10 dataset and saved the weights as an h5 file (keras_cifar10_trained_model.h5). When I load it in Keras and try to use Foolbox to generate adversarial examples, I get the above error. My code is as follows:

from foolbox.criteria import TargetClassProbability
from foolbox.attacks import LBFGSAttack
from foolbox.models import KerasModel

preprocessing = (np.array([104, 116, 123]), 1)
base_model = load_model('keras_cifar10_trained_model.h5')
fmodel = KerasModel(base_model, bounds=(0,1), preprocessing=preprocessing)

target_class = 5
criterion = TargetClassProbability(target_class, p=0.99)

attack = LBFGSAttack(base_model, criterion)
base_img = preprocess_image('airplane1.jpg')
label = 0
adversarial = attack(base_img[0,:,:,:], label=label)

I get the error on the last line. I tried searching through the documentation for Keras and couldn't find the 'bounds' variable anywhere. How do I fix this?

**Comment by wusf18** [comment]
Hello ! I meet the same problem new, have you solved it yet ? Thanks!

**Comment by jonasrauber** [comment]
You should pass the foolbox model to the attack, not the Keras model (or whatever framework you are using). In the code above that means that you should pass `fmodel` and not `base_model` to LBFGSAttack.
