### ISSUE TITLE
Warning of suboptimal results from PGD attack because distance metric was not specified as Linfinity

### ISSUE THREAD

**Issue by thelittlekid** [bethgelab/foolbox#280]
A warning showed up when I tried the ProjectedGradientDescentAttack(): 

`WARNING:root:Running an attack that tries to minimize the Linfinity norm of the perturbation without specifying foolbox.distances.Linfinity as the distance metric might lead to suboptimal results.`

Could you please post a simple example on how to set the distance metric? Thanks!

**Comment by jonasrauber** [comment]
You can pass it to the attack constructor, see here: https://foolbox.readthedocs.io/en/latest/modules/attacks/gradient.html#foolbox.attacks.ProjectedGradientDescentAttack

**Comment by jonasrauber** [comment]
Please reopen if this doesn't answer your question.

**Comment by MalharJ** [comment]
How can we specify what the Linfinity should be?

**Comment by xaohuicai** [comment]
> A warning showed up when I tried the ProjectedGradientDescentAttack():
> 
> `WARNING:root:Running an attack that tries to minimize the Linfinity norm of the perturbation without specifying foolbox.distances.Linfinity as the distance metric might lead to suboptimal results.`
> 
> Could you please post a simple example on how to set the distance metric? Thanks!

Have you solve this problem? I meet the same,but I can't deal this.

**Comment by jonasrauber** [comment]
The readme contains an example for setting the distance 😉

**Comment by xaohuicai** [comment]
> The readme contains an example for setting the distance

Thank you.Could you tell me some details?I tried it but it also didn't work.

**Comment by jonasrauber** [comment]
Can you be more specific? What didn't work? The code in the README?

**Comment by ziqi-zhang** [comment]
Hi @thelittlekid sorry to interrupt. The page you gave seems not to exist. I guess maybe you changed the address of the website? Can you please give me an updated address?
![image](https://user-images.githubusercontent.com/17118335/77653679-01e38480-6fab-11ea-8d1c-85a205e4f6f5.png)

**Comment by thelittlekid** [comment]
Hi @ziqi-zhang, I was actually the one who raised the issue. 
I believe they are renamed as `Lin2ProjectedGradientDescentAttack` or `LinfProjectedGradientDescentAttack`, and you may find them at https://foolbox.readthedocs.io/en/stable/modules/attacks.html#foolbox.attacks

**Comment by ziqi-zhang** [comment]
@thelittlekid Thanks so much!
