### ISSUE TITLE
Attack ensemble Pytorch models

### ISSUE THREAD

**Issue by xuguozhi** [bethgelab/foolbox#290]
How to ensemble different robust models to generate adversarial perturbations?

**Comment by jonasrauber** [comment]
You could try defining a new PyTorch model that uses other models internally

**Comment by xuguozhi** [comment]
Thx, I will try that method, any hint about using other models internally by Pytorch?

**Comment by jonasrauber** [comment]
Closing for now. Please reopen if this is still relevant.
