### ISSUE TITLE
Error with FGSM on MNIST in PyTorch

### ISSUE THREAD

**Issue by MalharJ** [bethgelab/foolbox#293]
I'm using a CNN on MNIST in PyTorch on Ubuntu 16.04 and in PyTorch. After loading it, I try to use the FGSM attack to generate adversarial samples. I'm running into the following issue:
```

import torch
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import argparse
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms

transform = transforms.Compose([transforms.ToTensor()])

trainset = torchvision.datasets.MNIST(root='./data', train=True, download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=1, shuffle=True, num_workers=2)
testset = torchvision.datasets.MNIST(root='./data', train=False, download=True,transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=1, shuffle=False, num_workers=2)

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5, 1)
        self.conv2 = nn.Conv2d(20, 50, 5, 1)
        self.fc1 = nn.Linear(4*4*50, 500)
        self.fc2 = nn.Linear(500, 10)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.max_pool2d(x, 2, 2)
        x = F.relu(self.conv2(x))
        x = F.max_pool2d(x, 2, 2)
        x = x.view(-1, 4*4*50)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)
    
net = Net()

import foolbox
import torchvision.models as models
import numpy as np
import torch

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

model = Net()
model.load_state_dict(torch.load('mnist_cnn.pt'))
model.to(device)
model.eval()

attacked_model = foolbox.models.PyTorchModel(model, bounds=(0,1), num_classes=10)
FGSM_attack = foolbox.attacks.FGSM(attacked_model)

dataiter = iter(trainloader)
img, label = dataiter.next()
img,label = img.to(device), label.to(device)

img_numpy = img.cpu().numpy()
label_numpy = label.cpu().numpy()

print (img_numpy.shape, type(img_numpy), label_numpy.shape, type(label_numpy))
print (label)
print (model(img))

adversarial = FGSM_attack(img_numpy, label)
```

This is my output:
```
(1, 1, 28, 28) <class 'numpy.ndarray'> (1,) <class 'numpy.ndarray'>
tensor([2], device='cuda:0')
tensor([[ -9.0029, -10.5157,  -0.0223,  -9.8003, -14.5975, -14.7177, -15.9099,
          -3.8259, -12.6854, -14.2094]], device='cuda:0',
       grad_fn=<LogSoftmaxBackward>)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-34-c36d09c54f78> in <module>
     71 print (model(img))
     72 
---> 73 adversarial = FGSM_attack(img_numpy, label_numpy)

~/.local/lib/python3.5/site-packages/foolbox/attacks/base.py in wrapper(self, input_or_adv, label, unpack, **kwargs)
    122                                      ' instance.')
    123                 a = Adversarial(model, criterion, input_or_adv, label,
--> 124                                 distance=distance, threshold=threshold)
    125 
    126         assert a is not None

~/.local/lib/python3.5/site-packages/foolbox/adversarial.py in __init__(self, model, criterion, original_image, original_class, distance, threshold, verbose)
     85         # check if the original image is already adversarial
     86         try:
---> 87             self.predictions(original_image)
     88         except StopAttack:
     89             # if a threshold is specified and the original input is

~/.local/lib/python3.5/site-packages/foolbox/adversarial.py in predictions(self, image, strict, return_details)
    303 
    304         self._total_prediction_calls += 1
--> 305         predictions = self.__model.predictions(image)
    306         is_adversarial, is_best, distance = self.__is_adversarial(
    307             image, predictions, in_bounds)

~/.local/lib/python3.5/site-packages/foolbox/models/base.py in predictions(self, image)
    158 
    159         """
--> 160         return np.squeeze(self.batch_predictions(image[np.newaxis]), axis=0)
    161 
    162     @abstractmethod

~/.local/lib/python3.5/site-packages/foolbox/models/pytorch.py in batch_predictions(self, images)
     86             predictions = predictions.data
     87         else:
---> 88             predictions = self._model(images)
     89             # TODO: add no_grad once we have a solution
     90             # for models that require grads internally

~/.local/lib/python3.5/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

<ipython-input-34-c36d09c54f78> in forward(self, x)
     28 
     29     def forward(self, x):
---> 30         x = F.relu(self.conv1(x))
     31         x = F.max_pool2d(x, 2, 2)
     32         x = F.relu(self.conv2(x))

~/.local/lib/python3.5/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

~/.local/lib/python3.5/site-packages/torch/nn/modules/conv.py in forward(self, input)
    318     def forward(self, input):
    319         return F.conv2d(input, self.weight, self.bias, self.stride,
--> 320                         self.padding, self.dilation, self.groups)
    321 
    322 

RuntimeError: Expected 4-dimensional input for 4-dimensional weight [20, 1, 5, 5], but got 5-dimensional input of size [1, 1, 1, 28, 28] instead
```

Why does it say that the input is 5 dimensional? I printed the shape of img out and its 4D. Running inference on img works fine, as shown in one of the print statements also.

Thanks!

**Comment by jonasrauber** [comment]
`img`, `label`, `img_numpy` and `label_numpy` are all batches. You should pass a single image and label. Alternatively, you can try the batch support, but it's still work in progress.

**Comment by skudekar** [comment]
I'm facing the same issue as above. I have checked that I'm passing a single image and label and so does the above code. Can somebody help resolve this issue?

**Comment by skudekar** [comment]
> I'm using a CNN on MNIST in PyTorch on Ubuntu 16.04 and in PyTorch. After loading it, I try to use the FGSM attack to generate adversarial samples. I'm running into the following issue:
> 
> ```
> 
> import torch
> import torchvision
> import torchvision.transforms as transforms
> import matplotlib.pyplot as plt
> import argparse
> import torch.nn as nn
> import torch.nn.functional as F
> import torch.optim as optim
> from torchvision import datasets, transforms
> 
> transform = transforms.Compose([transforms.ToTensor()])
> 
> trainset = torchvision.datasets.MNIST(root='./data', train=True, download=True, transform=transform)
> trainloader = torch.utils.data.DataLoader(trainset, batch_size=1, shuffle=True, num_workers=2)
> testset = torchvision.datasets.MNIST(root='./data', train=False, download=True,transform=transform)
> testloader = torch.utils.data.DataLoader(testset, batch_size=1, shuffle=False, num_workers=2)
> 
> class Net(nn.Module):
>     def __init__(self):
>         super(Net, self).__init__()
>         self.conv1 = nn.Conv2d(1, 20, 5, 1)
>         self.conv2 = nn.Conv2d(20, 50, 5, 1)
>         self.fc1 = nn.Linear(4*4*50, 500)
>         self.fc2 = nn.Linear(500, 10)
> 
>     def forward(self, x):
>         x = F.relu(self.conv1(x))
>         x = F.max_pool2d(x, 2, 2)
>         x = F.relu(self.conv2(x))
>         x = F.max_pool2d(x, 2, 2)
>         x = x.view(-1, 4*4*50)
>         x = F.relu(self.fc1(x))
>         x = self.fc2(x)
>         return F.log_softmax(x, dim=1)
>     
> net = Net()
> 
> import foolbox
> import torchvision.models as models
> import numpy as np
> import torch
> 
> device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
> 
> model = Net()
> model.load_state_dict(torch.load('mnist_cnn.pt'))
> model.to(device)
> model.eval()
> 
> attacked_model = foolbox.models.PyTorchModel(model, bounds=(0,1), num_classes=10)
> FGSM_attack = foolbox.attacks.FGSM(attacked_model)
> 
> dataiter = iter(trainloader)
> img, label = dataiter.next()
> img,label = img.to(device), label.to(device)
> 
> img_numpy = img.cpu().numpy()
> label_numpy = label.cpu().numpy()
> 
> print (img_numpy.shape, type(img_numpy), label_numpy.shape, type(label_numpy))
> print (label)
> print (model(img))
> 
> adversarial = FGSM_attack(img_numpy, label)
> ```
> 
> This is my output:
> 
> ```
> (1, 1, 28, 28) <class 'numpy.ndarray'> (1,) <class 'numpy.ndarray'>
> tensor([2], device='cuda:0')
> tensor([[ -9.0029, -10.5157,  -0.0223,  -9.8003, -14.5975, -14.7177, -15.9099,
>           -3.8259, -12.6854, -14.2094]], device='cuda:0',
>        grad_fn=<LogSoftmaxBackward>)
> 
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-34-c36d09c54f78> in <module>
>      71 print (model(img))
>      72 
> ---> 73 adversarial = FGSM_attack(img_numpy, label_numpy)
> 
> ~/.local/lib/python3.5/site-packages/foolbox/attacks/base.py in wrapper(self, input_or_adv, label, unpack, **kwargs)
>     122                                      ' instance.')
>     123                 a = Adversarial(model, criterion, input_or_adv, label,
> --> 124                                 distance=distance, threshold=threshold)
>     125 
>     126         assert a is not None
> 
> ~/.local/lib/python3.5/site-packages/foolbox/adversarial.py in __init__(self, model, criterion, original_image, original_class, distance, threshold, verbose)
>      85         # check if the original image is already adversarial
>      86         try:
> ---> 87             self.predictions(original_image)
>      88         except StopAttack:
>      89             # if a threshold is specified and the original input is
> 
> ~/.local/lib/python3.5/site-packages/foolbox/adversarial.py in predictions(self, image, strict, return_details)
>     303 
>     304         self._total_prediction_calls += 1
> --> 305         predictions = self.__model.predictions(image)
>     306         is_adversarial, is_best, distance = self.__is_adversarial(
>     307             image, predictions, in_bounds)
> 
> ~/.local/lib/python3.5/site-packages/foolbox/models/base.py in predictions(self, image)
>     158 
>     159         """
> --> 160         return np.squeeze(self.batch_predictions(image[np.newaxis]), axis=0)
>     161 
>     162     @abstractmethod
> 
> ~/.local/lib/python3.5/site-packages/foolbox/models/pytorch.py in batch_predictions(self, images)
>      86             predictions = predictions.data
>      87         else:
> ---> 88             predictions = self._model(images)
>      89             # TODO: add no_grad once we have a solution
>      90             # for models that require grads internally
> 
> ~/.local/lib/python3.5/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
>     487             result = self._slow_forward(*input, **kwargs)
>     488         else:
> --> 489             result = self.forward(*input, **kwargs)
>     490         for hook in self._forward_hooks.values():
>     491             hook_result = hook(self, input, result)
> 
> <ipython-input-34-c36d09c54f78> in forward(self, x)
>      28 
>      29     def forward(self, x):
> ---> 30         x = F.relu(self.conv1(x))
>      31         x = F.max_pool2d(x, 2, 2)
>      32         x = F.relu(self.conv2(x))
> 
> ~/.local/lib/python3.5/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
>     487             result = self._slow_forward(*input, **kwargs)
>     488         else:
> --> 489             result = self.forward(*input, **kwargs)
>     490         for hook in self._forward_hooks.values():
>     491             hook_result = hook(self, input, result)
> 
> ~/.local/lib/python3.5/site-packages/torch/nn/modules/conv.py in forward(self, input)
>     318     def forward(self, input):
>     319         return F.conv2d(input, self.weight, self.bias, self.stride,
> --> 320                         self.padding, self.dilation, self.groups)
>     321 
>     322 
> 
> RuntimeError: Expected 4-dimensional input for 4-dimensional weight [20, 1, 5, 5], but got 5-dimensional input of size [1, 1, 1, 28, 28] instead
> ```
> 
> Why does it say that the input is 5 dimensional? I printed the shape of img out and its 4D. Running inference on img works fine, as shown in one of the print statements also.
> 
> Thanks!

Hi Malhar, 

Did you solve this issue? I'm facing the same issue when I try to run foolbox attack in pytorch. I tried to reshape the img_numpy but it still gives some errors. If you have managed to resolve this issue, could you please let me know? Much appreciated! Thanks!

**Comment by jonasrauber** [comment]
@skudekar If you use the non-batch attacks, your image should not have a batch dimension.

**Comment by skudekar** [comment]
> @skudekar If you use the non-batch attacks, your image should not have a batch dimension.

Thanks for the reply. I agree with your comment. However, I tried by reshaping the img_numpy (which is (1,28,28,1) numpy array) in different ways as follows:
(*) **adversarial = FGSM_attack(img_numpy.reshape((28,28)), label_numpy)**
I get error: RuntimeError: Expected 4-dimensional input for 4-dimensional weight 20 1 5, but got 3-dimensional input of size [1, 28, 28] instead

(*) **adversarial = FGSM_attack(img_numpy.reshape((1,28,28)), label_numpy)**
I get error: ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 500])

(*)  **adversarial = FGSM_attack(img_numpy.reshape((28,28,1)), label_numpy)**
I get error: RuntimeError: Given groups=1, weight of size 20 1 5 5, expected input[1, 28, 28, 1] to have 1 channels, but got 28 channels instead

So I'm confused how should I remove the batch dimension as you suggest. Anything I try, I get the error above. 

Any help/suggestion would be much appreciated. I'm kind of stuck in a hole for a few days now. Again, thanks for your time and attention.

**Comment by jonasrauber** [comment]
The second one is correct: `(1, 28, 28)`, because you are using PyTorch and it expects channels first: (N)CHW-format.
Please share the full error message and stacktrace for that case. Have you tested your network without foolbox?

**Comment by skudekar** [comment]
@jonasrauber Thanks a lot for your message and sorry for delayed response. I actually managed to get it working with the following code. The troublemaker was that reshaping it (to (1,28,28) as you suggested above) also gave errors. But if I simply use: 
img = x_numpy[i,:,:,:]
lbl = y_numpy[i]

That seemed to work. Not sure why. 

I didn't run it without foolbox. I'm not completely confident in my ability to write an independent code :-). But this seems to work now. Thanks again a lot for your help and suggestions. 

``` python

import foolbox
import torch as th
attacked_model = foolbox.models.PyTorchModel(model, bounds=(0,255), num_classes=10)
FGSM_attack = foolbox.attacks.FGSM(attacked_model)

model.eval()
maxb = int(math.ceil(test_loader.n/opt['b']))
device = th.device("cuda:0" if th.cuda.is_available() else "cpu")
fgsm_err = 0.0
x_adv = []
for bi in range(maxb):
        x,y = next(test_loader)
        bsz = x.size(0)
        if opt['cuda']:
            x,y = x.cuda(), y.cuda()

        x,y =   Variable(x, volatile=True), \
                Variable(y.squeeze(), volatile=True)
                
        x_numpy = x.cpu().numpy()
        y_numpy = y.cpu().numpy()
        for i in range(x_numpy.shape[0]):
            img = x_numpy[i,:,:,:]
            lbl = y_numpy[i]
            adversarial = FGSM_attack(img, lbl)
            if adversarial is not None:
                adv = adversarial.reshape(1,1,28,28)
                im = th.from_numpy(adv).to(device)
                yh = model(im)
                temp_lbl = np.asarray(lbl)
                lb = th.from_numpy(temp_lbl).to(device)
                lb = lb.unsqueeze(0)
                f = criterion.forward(yh, lb).data
                prec1 = accuracy(yh.data, lb.data, topk=(1,))
                err = 100-prec1[0]
                fgsm_err += err
                x_adv.append(adversarial.reshape((784,)))
            else:
                x_adv.append(img.reshape((784,)))
        print('batch %d done'%bi)
        
fgsm_err = fgsm_err/test_loader.n
```

**Comment by jonasrauber** [comment]
Great, thanks for the update!
P.S. you can simplify your code quite a bit by simply using `attacked_model.forward` to get predictions for adversarials, etc.; and you can simplify it even more by using Foolbox 2.0 and batches. The whole example should just be 4 or 5 lines or so (see e.g. README).

**Comment by skudekar** [comment]
@jonasrauber Thanks for the batch attack tip! Should simplify the code a lot as you suggested. Again, thanks for taking out time to help. Much appreciated!
