### ISSUE TITLE
How to attack facenet using foolbox

### ISSUE THREAD

**Issue by littleredhat1997** [bethgelab/foolbox#294]
`vector_128 = model.predict(face)`
facenet output is not a classification result, but a 128-dimensional vector.

`adversarial = attack(face, vector_128)`
attack need a label parameter. if i set the output vector as label, it will error:

```
225             predictions, self.__original_class)
    226         assert isinstance(is_adversarial, bool) or \
--> 227             isinstance(is_adversarial, np.bool_)
    228         if is_adversarial:
    229             is_best, distance = self.__new_adversarial(
```

so how to attack facenet using foolbox?

**Comment by jonasrauber** [comment]
Foolbox is currently mostly focussed on adversarial attacks against classifiers. Everything else might require some modifications.
Is the 128-dimensional vector representing different classes?
In any case, the model output should not be passed to the attack. Instead, the ground truth output should be passed to it.
