### ISSUE TITLE
Why the model predictions are different every time?

### ISSUE THREAD

**Issue by PopeJoey** [bethgelab/foolbox#300]
Hi, I'm using the foolbox to generate JSMA adversarial examples  and my model is a resnet defined and trained in keras. Before generating and testing adversarial, I test my model predictions and the keras wrapper model predictions.My pretrained model has the right result and the wrapper model outputs different predictions with the same code everytime, which is really strange.Here are the sample code and outputs.
![image](https://user-images.githubusercontent.com/19484363/56456806-2c44bf00-63a4-11e9-95c7-0d9e8344b4e1.png)
![image](https://user-images.githubusercontent.com/19484363/56456809-35359080-63a4-11e9-8a50-cfa5e9cf9458.png)
The second output:
![image](https://user-images.githubusercontent.com/19484363/56456831-76c63b80-63a4-11e9-8c8c-4bbb42c52555.png)

**Comment by machengcheng2016** [comment]
I've met the same situation. Why did you close this issue?

**Comment by machengcheng2016** [comment]
I've met the same situation. What's the solution to this?

**Comment by PopeJoey** [comment]
> I've met the same situation. What's the solution to this?

Because I have find the reason of my sample code. The model  resnet that I want to wrap is not exactly the pure keras type , which  actually this foolbox need. The code line is 10 in first image. The strange thing is that codes run and don't throw an exception but give different result everytime. Maybe you can check you model type.
