### ISSUE TITLE
inconsistent keras model with fmodel created by foolbox

### ISSUE THREAD

**Issue by mhsamavatian** [bethgelab/foolbox#303]
I used VGG16 and resnet in keras to perform some of the attacks and I observed that the KerasModel returned by foolbox doest act same as the main model meaning that it does not predict the same labels as the main model does. What is the problem here? 

as a sample code:
preprocessing = (mean, std)
fmodel = foolbox.models.KerasModel(kmodel, bounds=(0, 255),preprocessing=preprocessing)
fmodel and kmodel are not same. 
this is before any attack. even after feeding adversarial image to fmodel and kmodel adversarial is not successful on kmodel.

**Comment by jonasrauber** [comment]
You told Foolbox about your preprocessing and thus it automatically takes care of it, i.e. you can use `fmodel` and can just pass it the raw images. For your `kmodel`, you need to do the preprocessing yourself before passing something to it.
