### ISSUE TITLE
Save the Adversarial Image

### ISSUE THREAD

**Issue by fbehnia** [bethgelab/foolbox#308]
Hello,

I am using alexnet on pytorch to make adversary images.

this is my code:

  ```
attack=foolbox.attacks.BasicIterativeMethod(model=fmodel,criterion=TargetClassProbability(781, p=.5))
    adversarial = attack(image, label,epsilon=epsilon)
    
    print (type(adversarial))
    
    if isinstance(adversarial, np.ndarray):
      print('adversarial class', np.argmax(fmodel.predictions(adversarial)))
```
then I want to save the adversary image to use in another model.

I use cv2 to do this:
    ```
 ```
 img = adversarial.transpose(1,2,0)
 cv2.imwrite(new_path,img)
```

But when loading the adversary label is completely changed. it classifies at 664.
Any ideas how to save the adversary image?

**Comment by jonasrauber** [comment]
answered via email

**Comment by MojsaKirill** [comment]
> answered via email

Can you help me? I have this is problem too

**Comment by kishordgupta** [comment]
I also have this problem

**Comment by MojsaKirill** [comment]
> I also have this problem

Hi. An image is an array of numbers. When working with the foolbox, the array looks like this [244,213 189,123 ...] When you save the image to the hard disk, the picture is cut to [244, 213 ...] This is the whole problem. You can save the image as a numpy array and then everything will work fine. Good luck
