### ISSUE TITLE
Is there a way to get the intermediate image during attacking?

### ISSUE THREAD

**Issue by Marvinmw** [bethgelab/foolbox#321]
Is there a way to get the intermediate image during attacking?

**Comment by ChengruiMeng** [comment]
you can try this way like I do, during the "For" circulate :
`if( step < "some number" or distance.value<"some value"):
                                perturbed1 = (new_perturbed/2)+0.5
                                plt.imshow(perturbed1)
                                plt.axis('off')
                                fig = matplotlib.pyplot.gcf()
                                plt.imsave(save_dir, perturbed1, format="jpeg")
                                plt.close()`

**Comment by jonasrauber** [comment]
One way to perform some operation on all intermediate values is by overriding the `Adversarial` class calling the attack with an explicit instance of it.
