### ISSUE TITLE
Parallel attacks with estimated gradients model

### ISSUE THREAD

**Issue by pchug13** [bethgelab/foolbox#322]
Hi, I have tested the newest version of Foolbox and it seems like it can't handle parallel batch attacks with estimated gradients models, any idea on when it will be released?

**Comment by wielandbrendel** [comment]
@pchug13 That's great feedback, could you post a minimal example for us to check? Not all features are yet implemented and ready for the batch-based version of Foolbox, which is partially why we only pre-released this version yet.

**Comment by pchug13** [comment]
Here is some code I tried to run:
`
model = ...
fmodel = foolbox.models.PyTorchModel(model, bounds=(0., 1.), num_classes=10, device=u.dev())
GE = foolbox.gradient_estimators.CoordinateWiseGradientEstimator(0.1)
fmodel = foolbox.models.ModelWithEstimatedGradients(fmodel, GE)

inputs, labels = ...
attack = foolbox.batch_attacks.GradientAttack
criterion = foolbox.criteria.Misclassification()
advs = run_parallel(attack, fmodel, criterion, inputs, labels)
`

Running this code I get a NotImplementedError coming from foolbox/batching.py line 95:
`gradients = model.gradient(*gradients_args)`

It makes sense as when you take a look at foolbox/models/wrappers.py for ModelWithEstimatedGradients the gradient function raises a NotImplementedError if there is more than one input.
