### ISSUE TITLE
AttributeError: 'PyTorchModel' object has no attribute 'forward_one'

### ISSUE THREAD

**Issue by haim-barad** [bethgelab/foolbox#328]
I'm trying to use a resnet50 (imagenet) and perform some simple attacks - however, I can't even get the samples in the docs working:

> (Pdb) print(fmodel)
> 
> <foolbox.models.pytorch.PyTorchModel object at 0x7ff7e59b3be0>
> (Pdb) print(dir(fmodel))
> ['__abstractmethods__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_abc_cache', '_abc_negative_cache', '_abc_negative_cache_version', '_abc_registry', '_bounds', '_channel_axis', '_loss_fn', '_model', '_num_classes', '_old_pytorch', '_preprocessing', '_process_gradient', '_process_input', 'backward', 'batch_predictions', 'bounds', 'channel_axis', 'device', 'gradient', 'num_classes', 'predictions', 'predictions_and_gradient']
> (Pdb) 

and then when I try to do 
> print('predicted class', np.argmax(fmodel.forward_one(fimage)))

I get the error 
> AttributeError: 'PyTorchModel' object has no attribute 'forward_one'

The code is below:

> 215  	            # adversarial attacks and testing via foolbox
> 216  	        mean = np.array([0.485, 0.456, 0.406]).reshape((3, 1, 1))
> 217  	        std = np.array([0.229, 0.224, 0.225]).reshape((3, 1, 1))
> 218  	        model.eval()
> 219  	        fmodel = foolbox.models.PyTorchModel(
> 220  	            model, bounds=(0, 1), num_classes=1000, preprocessing=(mean, std))
> 221  	
> 222  	
> 223  	        # get source image and label
> 224 B	        fimage, flabel = foolbox.utils.imagenet_example(data_format='channels_first')
> 225  	        fimage = fimage / 255.  # because our model expects values in [0, 1]
> (Pdb) 
> 226  	
> 227  	        print('label', flabel)
> 228  ->	        print('predicted class', np.argmax(fmodel.forward_one(fimage)))
> 229  	
> 230  	        # apply attack on source image
> 231  	        attack = foolbox.attacks.FGSM(fmodel)
> 232  	        adversarial = attack(fimage, flabel)
> 233  	
> 234  	        print('adversarial class', np.argmax(fmodel.forward(adversarial)))
> 

The error occurs on the last line (234) - I'm sure there's some small typo, bad indent, etc. Has anyone run into this?

Is there a difference between the current code base and the version you get when running "pip install foolbox"?

**Comment by haim-barad** [comment]
I found my own mistake. Closing issue. I had installed via "pip install foolbox" and also via setup.py - this was a mistake and the versions aren't compatible. 

Issue closed.

**Comment by aicools** [comment]
How did you solve this problem
