### ISSUE TITLE
LocalSearchAttack is not available on Pytorch model

### ISSUE THREAD

**Issue by machengcheng2016** [bethgelab/foolbox#330]
My example script is shown below:
![image](https://user-images.githubusercontent.com/22851860/59972684-2ea2df80-95c6-11e9-9417-073d98f7eadd.png)

Then there is no adversarial sample generated, leading to the 'NoneType' error.
![image](https://user-images.githubusercontent.com/22851860/59972693-6ca00380-95c6-11e9-97e0-19443cadc8a2.png)

I've also test 800 images from ImageNet validation dataest on VGG-16 Pytorch model, and still not a single adversarial image is generated.
On the other hand, I've also test LocalSearchAttack on Keras model, and it works properly. 
This example script is just copied from https://foolbox.readthedocs.io/en/latest/user/examples.html. 
Why is LocalSearchAttack not available on Pytorch model? Please give me a hand. Thanks!

**Comment by jonasrauber** [comment]
Sounds like this is some other problem. I am closing this for now, assuming it is no longer an issue. Please reopen if it still is.
