### ISSUE TITLE
Can't instantiate abstract class

### ISSUE THREAD

**Issue by peglegpete** [bethgelab/foolbox#333]
Hello guys,

Thank you for this interesting repo.

I am trying to make some adjustments to the `KerasModel` class. I do so by defining a new class `class KerasModelCustom(DifferentiableModel):` (see the attached `custom_keras.txt` - note: all I changed in the file from the original `KerasModel` class is the name)

[custom_keras.txt](https://github.com/bethgelab/foolbox/files/3331702/custom_keras.txt)

If I then try to use the new model object as such

`import foolbox`
`from custom_keras import *`
`fmodel = KerasModelCustom(model, bounds=(0., 1.), predicts='logits')`

I get the following error message

`TypeError: Can't instantiate abstract class KerasModelCustom with abstract methods batch_predictions, predictions_and_gradient`

Is this behavior intended? If so do you maybe have a pointer on how to customize model objects correctly?

Thanks for your help,
Pete

**Comment by jonasrauber** [comment]
I think you maybe rather want to subclass `KerasModel` instead of `DifferentiableModel`. But I am not sure why you need to that at all. Maybe explain what adjustments you need. Closing this for now, please reopen if it's still an issue. Thanks.
