### ISSUE TITLE
Batch Attack is equal to multiple single attack ???

### ISSUE THREAD

**Issue by Sunshine352** [bethgelab/foolbox#342]
Batch Attack is in practice implemented through generator using single attack multiple times? The  running time is as folows. So, what's the meaning by doing so???

### Single Attack(1*100)

| Method  |  FGSM   | GradientAttack |   PGD   | MI-FGSM | DeepFool | L-BFGS  |  JSMA   |  CW-L2  |  Adef   |
| :-----: | :-----: | :------------: | :-----: | :-----: | :------: | :-----: | :-----: | :-----: | :-----: |
|   ASR   | 100/100 |    100/100     | 100/100 | 100/100 |  90/100  | 100/100 | 100/100 | 100/100 | 88/100  |
| time(s) | 1.0290  |     0.9754     | 26.2580 | 13.5801 | 11.5079  | 37.2358 | 13.1846 | 77.0362 | 13.2869 |

### Batch Attack(batch-size=100, 100*1)

| Method  |  FGSM   | GradientAttack |   PGD   | MI-FGSM |  CW-L2  |   EAD   |
| :-----: | :-----: | :------------: | :-----: | :-----: | :-----: | :-----: |
|   ASR   | 100/100 |    100/100     | 100/100 | 100/100 | 100/100 | 100/100 |
| time(s) | 1.4682  |     0.9456     | 18.7944 | 5.2050  | 71.7168 | 37.5082 |

**Comment by Sunshine352** [comment]
time(s) is the time spent on each image.

**Comment by jonasrauber** [comment]
The automatic batching uses generators to get "candidates" from single attacks, but then runs them through the network in batches, which is the most expensive part (forward-pass to get predictions and backward-pass to get gradients). Regarding your numbers: maybe your model is small or you ran it just on CPU and it was already fully-utilized by a single attack; in our experiments batching is substantially faster.
