### ISSUE TITLE
WARNING:root:exponential search failed

### ISSUE THREAD

**Issue by xinhongri** [bethgelab/foolbox#344]
WARNING:root:exponential search failed

I  use  a bim targeted attack to see the waring above
and the attack is a failure
I don't know why.
Thank you!

**Comment by FlashTek** [comment]
Hi @xinhongri, this error indicates that foolbox was not able to find an adversarial example using the attack & parameter combination you've used. Without seeing a minimal working example to reproduce your issue we cannot give you any more help.

**Comment by jonasrauber** [comment]
Closing for now. See comment above.
