### ISSUE TITLE
DeepFool missing from batch_attacks

### ISSUE THREAD

**Issue by ezelikman** [bethgelab/foolbox#345]
DeepFool is one of the models which is currently missing from batch_attacks in 2.0.0 and seems like an important one to include

**Comment by FlashTek** [comment]
Hi @ezelikman, you are right, `DeepFool` is still missing in the latest version of foolbox and it's an important attack. We have started to port more of the attacks to the new batched mode; you can find the current state of this process in [PR 339 ](https://github.com/bethgelab/foolbox/pull/339) -  this PR already includes a working version of most of the attacks including `DeepFool` . We hope to finish migrating all existing attacks soon.

**Comment by jonasrauber** [comment]
#339 has been merged. Available on master and in the next 2.0 release.
