### ISSUE TITLE
Add support for different kwargs per attack in run_parallel and run_sequential

### ISSUE THREAD

**Issue by zimmerrol** [bethgelab/foolbox#349]
@jonasrauber I was thinking about whether we should extend the interface of the `run_parallel` method (defined in `batching.py`) so that users can not only pass one dictionary of additional attack arguments but a list of these dictionaries so that each attack can be called with an individual set of additional parameters (similar to how we have already extended the `criterion` argument to support such lists). This would make it easier to implement for example the attack described in [Adversarial Manipulation of Deep Representations](https://arxiv.org/abs/1511.05122) as here, one has to have access not only to the unperturbed version of the image but also to another clean image which features should be imitated. What are your thoughts on this?

**Comment by jonasrauber** [comment]
@FlashTek I like it! 👍

**Comment by FlashTek** [comment]
Great! I will start working on it once [PR 339](https://github.com/bethgelab/foolbox/pull/339) (the batched version of most attacks) is merged into master since it already contains some modifications in the batching system.
