### ISSUE TITLE
Batch generation of adversarial examples for any attack?

### ISSUE THREAD

**Issue by NullConvergence** [bethgelab/foolbox#357]
Hello! Is there an attack agnostic way to generate batch adversarial examples? 
This would be useful for adversarial training, testing ,etc.

Thanks!

**Comment by averyma** [comment]
I think the attacks that supported batch are under /foolbox/batch_attacks/.
So as of right now we are only limited to those.

**Comment by wielandbrendel** [comment]
We are in the middle of refactoring Foolbox and you'll see many more batch attacks very soon (within two to three weeks). Please stay tuned!

**Comment by jonasrauber** [comment]
Almost all attacks are now available as batch attacks on the master branch. Please reopen if this does not resolve this issue.
