### ISSUE TITLE
Inconsistency of target_class and original_class in Adversarial

### ISSUE THREAD

**Issue by zimmerrol** [bethgelab/foolbox#358]
I noticed that in the `Adversarial` class the interface to access the target class (if available) is given by
  
    def target_class(self):
       ...

while the original class is defined as a property

     @property
     def original_class(self):

Is there any reason for this that I am missing right now or is this not intended? Should we define the target class as a property as well @jonasrauber ?

**Comment by jonasrauber** [comment]
I agree, we should make this more consistent.
