### ISSUE TITLE
Model with single sigmoid output for binary clasification

### ISSUE THREAD

**Issue by TheGuywithTheHat** [bethgelab/foolbox#360]
I have a keras model for binary classification, so it has a single sigmoid output. I turn it into a foolbox model like so: `foolbox.models.KerasModel(my_model, bounds=(-5, 5))`. When attempting attacks, I get the warning: `Not running the attack because the original input is already misclassified and the adversarial thus has a distance of 0.`

Is a single sigmoid supposed to work by default, or is my attempt to do that the cause of the warning? If that does not work by default, is there any way to feed this model directly to foolbox, or do I need to add a second output that is `1 - the first output`?

**Comment by jonasrauber** [comment]
You should add a second output.
