### ISSUE TITLE
Support  for TF2

### ISSUE THREAD

**Issue by suneeta-mall** [bethgelab/foolbox#365]
Are there any plans to support Tensorflow 2? Looks like underlined API used are  still 1.X /14 based? 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-feb4bd2aa3f9> in <module>
      6 
      7 for img, mask in test_dataset.take(50):
----> 8     with foolbox.models.TensorFlowModel(img, mask, (0, 1)) as model:
      9         restorer.restore(model.session, 'mymodel.h5')
     10         print(np.argmax(model.predictions(img)))

~/miniconda3/envs/tf2/lib/python3.7/site-packages/foolbox/models/tensorflow.py in __init__(self, inputs, logits, bounds, channel_axis, preprocessing)
     43         import tensorflow as tf
     44 
---> 45         session = tf.get_default_session()
     46         if session is None:
     47             logging.warning('No default session. Created a new tf.Session. '

AttributeError: module 'tensorflow' has no attribute 'get_default_session'
```

**Comment by suneeta-mall** [comment]
sorry I opened this too soon ..  found  `TensorFlowEagerModel`

**Comment by suneeta-mall** [comment]
Seeing this error now:
```
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'min'
```

**Comment by jonasrauber** [comment]
We certainly want to support TF2. The `TensorFlowEagerModel` was built when Eager support was added to TF1. There might some issues with using TF2 at the moment, but if you could provide a better example reproducing the error (+ concrete version numbers) we would be happy to fix these problems as soon as possible.

**Comment by suneeta-mall** [comment]
@jonasrauber Ah right! Just whipped up this example:

```
import tensorflow as tf
import tensorflow_datasets as tfds

import foolbox
from foolbox.criteria import Misclassification	
from foolbox.attacks import FGSM
from foolbox.models import TensorFlowEagerModel


def normalize(input_image, label):
  input_image = tf.cast(input_image, tf.float32) / 255.0
  label -= 1
  return input_image, label

@tf.function
def load_image_test(datapoint):
  input_image = tf.image.resize(datapoint['image'], (128, 128))
  label = datapoint['label']
  input_image, label = normalize(input_image, label)
  return input_image, label

dataset, info = tfds.load('oxford_iiit_pet:3.0.0', with_info=True)
test = dataset['test'].map(load_image_test)
test_dataset = test.batch(64)

model = tf.keras.applications.MobileNetV2(input_shape=(128,128,3))


fmodel = TensorFlowEagerModel(model, bounds=(0, 1))
attack = FGSM(fmodel, criterion=Misclassification())

for image, label in test_dataset.take(1):
	adversarial = attack(image, label)
```

As for version:
```
foolbox                  2.0.0b0
tensorboard              2.0.0
tensorflow               2.0.0
tensorflow-datasets      1.2.0
tensorflow-estimator     2.0.0
tensorflow-graphics      1.0.0
tensorflow-metadata      0.14.0
tensorflow-probability   0.8.0
```

**Comment by Djmcflush** [comment]
would be great! I am also having the same problem

**Comment by jonasrauber** [comment]
Great news. Foolbox works just fine with TensorFlow 2.0 and Eager Mode.

As you already noticed, the right model class to use is `TensorFlowEager`.

The reason why your code fails is a different one:
Your `tensorflow_datasets` based code returns tensors instead of arrays. You can fix this by replacing `attack(image, label)` with `attack(image.numpy(), label.numpy())`.
Furthermore, `image` and `label` in your code are actually batches of 64 images and labels, but the attack you use (`foolbox.attacks.FGSM`) expects just a single image and label.
If you just want to run it on a single image, change it to `attack(image.numpy()[0], label.numpy())[0]`. If you want to run it on the whole batch, replace `from foolbox.attacks import FGSM` with from `foolbox.batch_attacks import FGSM`

**Comment by suneeta-mall** [comment]
@jonasrauber oh my bad ..I would not have guessed it looking at error message ```AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'min'```

Thanks for looking into it .. I will try out further .. quick attempt gave weird classification outcome on adverserial image but I need to look at i t carefully.  I will reopen if see any more issues. Ta
