### ISSUE TITLE
Differentiate through preprocessing

### ISSUE THREAD

**Issue by ambrishrawat** [bethgelab/foolbox#40]
For the Resnet model, shouldn't the gradients be passed through the preprocessing_input?

**Comment by wielandbrendel** [comment]
Hey @ambrishrawat , very good point that we also discovered yesterday. I already opened a PR which will most likely be merged today. It changes the preprocessing a little bit as we can not allow arbitrary preprocessing functions.

**Comment by jonasrauber** [comment]
Thanks a lot @ambrishrawat.
@wielandbrendel fixed this in #39 and version 0.9.0 containing the fix was just released.
