### ISSUE TITLE
valueError: too many values to unpack 

### ISSUE THREAD

**Issue by huiminzeng** [bethgelab/foolbox#416]
This might be a bad question. I just can't get the code in your first example run.
'''
preprocessing = dict(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], axis=-3)
fmodel = foolbox.models.PyTorchModel(model, bounds=(0, 1), num_classes=1000, preprocessing=preprocessing)
'''

Am i missing something?

**Comment by jonasrauber** [comment]
What error message do you get?
