### ISSUE TITLE
how to modify the BoundaryAttack method to get positive disturbance

### ISSUE THREAD

**Issue by wayneowen7** [bethgelab/foolbox#417]
The model I want to attack is to classify a sequence of integers as input, but for the operational problems in related fields, the perturbation attack on the model can only positively perturb the integers, that is, only integers can be added. Can't add negative perturbations, is there any way or parameter in the BoundaryAttack  to achieve this idea?

**Comment by jonasrauber** [comment]
No, not out of the box, sorry. Maybe you can find some workaround (e.g. modifying your model).
