### ISSUE TITLE
About boundary attack parameters

### ISSUE THREAD

**Issue by schwarzichet** [bethgelab/foolbox#419]
I am trying to use boundary attack, while I am confused about the input parameters.
Follow the instruction on document, the input should be applied like
`
attack = foolbox.attacks.BoundaryAttack(fmodel)
`
`
adversarials = attack(input_or_adv=images, label=labels)
`
but I got such error message

> Traceback (most recent call last):
>   File "fooltest.py", line 19, in <module>
>     adversarials = attack(input_or_adv=images, label=labels)
> TypeError: __call__() missing 2 required positional arguments: 'inputs' and 'labels'

I guess the cause is that the document goes wrong when foolbox comes to v2.X?
and it should be
`attack = foolbox.attacks.BoundaryAttack(fmodel)`
`adversarials = attack(inputs=images, labels=labels)`

**Comment by jonasrauber** [comment]
Is this still relevant?
