### ISSUE TITLE
Exception after gradient becomes 0 in class SparseL1GradientMixin

### ISSUE THREAD

**Issue by gursimar** [bethgelab/foolbox#424]
File: foolbox\attacks\iterative_projected_gradient.py
Class: SparseL1GradientMixin

The statement `gradient = e / normalization` is problematic. For some inputs, when gradient becomes zero, the divide by zero falls into an exception.

Possible fix (although not sure of consequences)
`        if normalization == 0.0:
            normalization = 0.0001`

**Comment by jonasrauber** [comment]
Is this still relevant?
