### ISSUE TITLE
Targeted attack on batch

### ISSUE THREAD

**Issue by fvmassoli** [bethgelab/foolbox#425]
I am using toolbox to create adversarial samples for a pytorch model.
How can I use the Targeted criterion with a batch of images, i.e. by passing to it a batch of labels instead of just one?

**Comment by jonasrauber** [comment]
Is this still relevant?

**Comment by fvmassoli** [comment]
No, thanks. I found the way. 
I have another question though, and I don't know if it is the case to open a different issue (perhaps I am missing the correct piece in the code).
Is there a way to let foolbox returns an adversarial perturbation even if the attack did not succeed, instead of None?
Assume for example that I am running an untargeted attack and foolbox was not able to fool the model. Is it possible to return the perturbed image anyway?

**Comment by jonasrauber** [comment]
Not really in the current version, but with Foolbox 3 aka Foolbox Native this will be possible.

**Comment by giangnguyen2412** [comment]
still not possible now at the lastest version?
