### ISSUE TITLE
an operational problem(AssertionError )

### ISSUE THREAD

**Issue by 1993cathyzhao1993** [bethgelab/foolbox#427]
when I operate the py document,AssertionError will occur.and point to the line which has adversarial = attack(image[:, :, ::-1], label).I don't know why.and I can't google any solutions about this question.Please help me.thanks!

**Comment by MarkoOrescanin** [comment]
I have noticed the same issue when I pull down version 2.3...That attack statement will work in version 1.8

**Comment by MarkoOrescanin** [comment]
OK..use foolbox.v1.attacks emphasis on v1 ...that works. seems that there are differences in API.

**Comment by 1993cathyzhao1993** [comment]
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MarkoOrescanin"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月5日(星期四) 凌晨5:01
收件人:&nbsp;"bethgelab/foolbox"<foolbox@noreply.github.com&gt;;
抄送:&nbsp;"catcatcathy"<2570373207@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bethgelab/foolbox] an operational problem(AssertionError ) (#427)




OK..use foolbox.v1.attacks emphasis on v1 ...that works. seems that there are differences in API.

**Comment by 1993cathyzhao1993** [comment]
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MarkoOrescanin"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月5日(星期四) 凌晨4:51
收件人:&nbsp;"bethgelab/foolbox"<foolbox@noreply.github.com&gt;;
抄送:&nbsp;"catcatcathy"<2570373207@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bethgelab/foolbox] an operational problem(AssertionError ) (#427)




I have noticed the same issue when I pull down version 2.3...That attack statement will work in version 1.8
