### ISSUE TITLE
BoundaryAttack/LoacalSearchAttack breaks/error

### ISSUE THREAD

**Issue by MarkoOrescanin** [bethgelab/foolbox#428]
I am trying to run a boundry attack on VGG16 keras model. My image/model setup runs successfully on 
attack = foolbox.attacks.FGSM(fmodel, distance=foolbox.distances.Linf)
adversarials = attack(images[:16,], labels[:16], unpack=False)

However, when I switch attack to either of the two bellow my code breaks due to the 
resource exhausted error. Am I running attacks in the wrong manner such that i am exhausting resources?

attack = foolbox.attacks.BoundaryAttack(fmodel)
adversarials = attack(images[:2,], labels[:2], unpack=False)

or

attack = foolbox.attacks.LocalSearchAttack(fmodel)
adversarials = attack(images[:2,], labels[:2], unpack=False)

Error bellow: 

---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-10-433a5ec6ca27> in <module>
      1 attack = foolbox.attacks.LocalSearchAttack(fmodel)
----> 2 adversarials = attack(images[:2,], labels[:2], unpack=False)

~/anaconda2/envs/adversarial/lib/python3.6/site-packages/foolbox/attacks/base.py in __call__(self, inputs, labels, unpack, individual_kwargs, **kwargs)
     50             threshold=threshold,
     51             individual_kwargs=individual_kwargs,
---> 52             **kwargs,
     53         )
     54 

~/anaconda2/envs/adversarial/lib/python3.6/site-packages/foolbox/batching.py in run_parallel(create_attack_fn, model, criterion, inputs, labels, distance, threshold, verbose, individual_kwargs, **kwargs)
    337 
    338             # split super-batch back into individual batches
--> 339             batched_predictions = model.forward(inputs)
    340             batched_predictions = np.split(batched_predictions, batch_splits, axis=0)
    341 

~/anaconda2/envs/adversarial/lib/python3.6/site-packages/foolbox/models/keras.py in forward(self, inputs)
    129     def forward(self, inputs):
    130         px, _ = self._process_input(inputs)
--> 131         (predictions,) = self._forward_fn([px])
    132         assert predictions.shape == (inputs.shape[0], self.num_classes())
    133         return predictions

~/anaconda2/envs/adversarial/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in __call__(self, inputs)
   2713                 return self._legacy_call(inputs)
   2714 
-> 2715             return self._call(inputs)
   2716         else:
   2717             if py_any(is_tensor(x) for x in inputs):

~/anaconda2/envs/adversarial/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in _call(self, inputs)
   2673             fetched = self._callable_fn(*array_vals, run_metadata=self.run_metadata)
   2674         else:
-> 2675             fetched = self._callable_fn(*array_vals)
   2676         return fetched[:len(self.outputs)]
   2677 

~/anaconda2/envs/adversarial/lib/python3.6/site-packages/tensorflow/python/client/session.py in __call__(self, *args, **kwargs)
   1456         ret = tf_session.TF_SessionRunCallable(self._session._session,
   1457                                                self._handle, args,
-> 1458                                                run_metadata_ptr)
   1459         if run_metadata:
   1460           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[256,64,299,299] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node block1_conv2/convolution}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[256,64,299,299] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node block1_conv2/convolution}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[dense_3/BiasAdd/_477]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

**Comment by jonasrauber** [comment]
Is this still relevant?
