### ISSUE TITLE
DeepFool cannot works normally on GluonCV models

### ISSUE THREAD

**Issue by yqtianust** [bethgelab/foolbox#432]
Hi,

We applied Foolbox DeepFool attack on GluonCV models. The 1000 input images are selected from ImageNet. However, we cannot get a reasonable success rate on several models: densenet121/169/201, mobilenet, resnet50/101/152. 

For example: for model Desnet121, the success rate is only 0.0413971539 (32/773). And it takes quite a long time.
Experiment Setting: untargeted attack, with distance foolbox.distances.MSE, 

We can get reasonable success rates on vgg16/19 and alexnet. 

If we switch DeepFool to FGSM and BIM, all the above models work well. 

Thanks.

**Comment by jonasrauber** [comment]
Is this still relevant?
