### ISSUE TITLE
Boundary Attack sucked into an infinite loop

### ISSUE THREAD

**Issue by Gary-Shi** [bethgelab/foolbox#435]
Hi dear developers! I was trying BoundaryAttack in your library the other day. And I found that the process of searching adversarial perturbations was sucked into a infinite loop. 

For example, here is batch with 32 images. 4 of them are already misclassified by the model. And then the algorithm cannot find perturbations for remaining 28 images. 
Here are the outputs:

'''
Not running the attack because the original input is already misclassified and the adversarial thus has a distance of 0.
Not running the attack because the original input is already misclassified and the adversarial thus has a distance of 0.
Not running the attack because the original input is already misclassified and the adversarial thus has a distance of 0.
Not running the attack because the original input is already misclassified and the adversarial thus has a distance of 0.
4 of 32 attacks completed
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
Found adversarial input after 1 attempts
4 of 32 attacks completed
4 of 32 attacks completed
4 of 32 attacks completed
4 of 32 attacks completed
4 of 32 attacks completed
4 of 32 attacks completed
......

'''

**Comment by Gary-Shi** [comment]
It seems that the algorithm has actually found the remaining 28 perturbations (there were 28 lines of 'Found adversarial input after 1 attempts')
However it was sucked into an infinite loop after that...

**Comment by jonasrauber** [comment]
That's not an infinite loop, that's the actual attack (it takes a while). The "Found adversarial …" message is from the initialization attack (that's used to find the starting points, because you didn't provide any).
