### ISSUE TITLE
Foolbox - virtual adversarial attack gradient vanished 

### ISSUE THREAD

**Issue by VikramVashisth** [bethgelab/foolbox#437]
I am testing foolbox virtual adversarial attack and facing the gradient vanished error as mentioned in the image below. I need help to execute this attack type.

![image](https://user-images.githubusercontent.com/10899289/72273461-abf97480-362a-11ea-99af-1dd13aa8d18b.png)

Code used -
`def foolbox_attack_demo(attack_title, attack_type,images,labels):
    start_time = time.time()
    
    adversarials = attack_type(images, labels, unpack=False)
    
    distances = np.asarray([a.distance.value for a in adversarials])
    failed_attacks = sum(adv.distance.value == np.inf for adv in adversarials)
    accuracy_on_adversarial = (failed_attacks/len(adversarials))*100 
    
    time_taken = round((time.time() - start_time),2)
    
    print("Foolbox model: Accuracy on pertubed images: {} %, Time taken:{} seconds".format(accuracy_on_adversarial,time_taken))

    
    arr = []
    for each in range(len(adversarials)):
        
        #return predicted class if it exists else, return the original class 
        try:
            predicted_class = adversarials[each].output.argmax()
        except AttributeError:
            predicted_class =  adversarials[each].original_class
            
        #return preturbed image if it exists else, return the original image itself 
        try:
            preturbed_image = adversarials[each].perturbed.reshape(28,28)
        except AttributeError:
            preturbed_image = adversarials[each].unperturbed.reshape(28,28)

            
        arr.append((preturbed_image,
                    adversarials[each].unperturbed.reshape(28,28),
                    adversarials[each].original_class, 
                    predicted_class))

    #the actual adversarial images will be saved locally in a pickle file 
    
    timestamp=datetime.now().strftime("%d_%m_%Y_%H%M_%S")
    file_name = "data/Adversarial/foolboxadv_" +attack_title+ "_"+timestamp + ".pickle"
    pickle_file = open(file_name,"wb")
    pickle.dump(arr, pickle_file)
    pickle_file.close()
    print("Foolbox: Adversarials for " +attack_title + " saved as pickle file")
    

    return [attack_title,accuracy_on_adversarial, time_taken]

`

**Comment by jonasrauber** [comment]
If this is still relevant, please reopen.
