### ISSUE TITLE
randomgen version

### ISSUE THREAD

**Issue by hayabrama** [bethgelab/foolbox#438]
I couldn't run boundary attack using the latest version of randomgen. It worked after I uninstalled the package and then installed version 1.14.4, even though the requirements say randomgen>=1.14.4

**Comment by jonasrauber** [comment]
The latest version of `randomgen` made some incompatible changes. I think it can be easily fixed by changing the names.

**Comment by jonasrauber** [comment]
Let's keep it open until it's fixed. A PR would be great.

**Comment by jonasrauber** [comment]
fixed in Foolbox 2.4.0
