### ISSUE TITLE
How should I cite FoolBox?

### ISSUE THREAD

**Issue by marty1885** [bethgelab/foolbox#511]
Hi,

I'm using FoolBox in a adversarial example defensing project and are purposing to my advisor to turn the project into a paper. How should I cite FoolBox v3? Is there a preferred way to cite your work?Or is the v2 citation okay?

Best

**Comment by jonasrauber** [comment]
Foolbox: A Python toolbox to benchmark the robustness of machine learning models
Reliable Machine Learning in the Wild Workshop, 34th International Conference on Machine Learning, 2017

**BibTeX**
```
@inproceedings{rauber2017foolbox,
  title={Foolbox: A Python toolbox to benchmark the robustness of machine learning models},
  author={Rauber, Jonas and Brendel, Wieland and Bethge, Matthias},
  booktitle={Reliable Machine Learning in the Wild Workshop, 34th International Conference on Machine Learning},
  year={2017},
  url={http://arxiv.org/abs/1707.04131},
}
```

**Comment by marty1885** [comment]
Thanks!
