### ISSUE TITLE
is it a full tutorial? it does not work due to a function not defined

### ISSUE THREAD

**Issue by vietvo89** [bethgelab/foolbox#513]
Hi authors
Due to an issue with AttributeError: module 'tensorflow' has no attribute 'placeholder', I have to replace a line of code as below

#import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 

But I got another error and it seems that there is no where in your tutorial define it before. Can you check it?

5 images = tf.placeholder(tf.float32, (None, 224, 224, 3))
6 preprocessed = vgg_preprocessing(images)
7 logits = vgg19(preprocessed)

NameError: name 'vgg_preprocessing' is not defined

Thanks

Viet

**Comment by jonasrauber** [comment]
Could you clarify where you found this code snippet?

**Comment by vietvo89** [comment]
Sorry Jonas for my late response.
+ I followed the tutorial/exampls from the link below. It is a part of document of version 2.4 I guess. 
+ I tried installing both version 2.4 and 3.0 to run these codes but it seems that they do not work or  are not compatible.

1 - https://foolbox.readthedocs.io/en/stable/user/tutorial.html
2 - https://foolbox.readthedocs.io/en/stable/user/examples.html

+ For the tutorial in this repository, I ran it but when excuting the line. I got an error 

" fb.distances.l2(images, raw) "

-> ValueError: Unknown type: <class 'list'>

Thanks

Viet

**Comment by jonasrauber** [comment]
The two links to the `stable` documentation are currently for Foolbox 2. Everything should work, except for a few things like `vgg_preprocessing`: that's something you should replace with the actual preprocessing of your model.

`fb.distances.l2` is something from Foolbox 3 and should work there, but note that the inputs should be tensors with a batch dimension, not lists.

Sorry for the somewhat chaotic documentation at the moment, I hope to clean this up soon with the full release of Foolbox 3. Until then, for new projects I already recommend Foolbox 3 (you can change the docs on ReadTheDocs to `latest`; the Jupyter notebook linked in the README as tutorial should also work with the latest Foolbox 3 prerelease, I think.
