### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'num_classes'

### ISSUE THREAD

**Issue by JanineCHEN** [bethgelab/foolbox#520]
I have installed foolbox via `pip install foolbox==3.0.0b1`, while trying the execute 
`fmodel = fb.models.PyTorchModel(model, bounds=(0, 1), num_classes=10)` 
I got the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'num_classes'
```
Does the new version not supporting `num_classes` intake anymore??

**Comment by zimmerrol** [comment]
@jeffreyzpan You're right: in the latest version of foolbox you don't have to set the number of classes manually but it will be inferred by the output shape of your model.

**Comment by jonasrauber** [comment]
I think this is solved. `num_classes` is not needed anymore and the docs should reflect this. If `num_classes` is still used in the docs somewhere, let us know. Thanks!
