### ISSUE TITLE
Limiting the perturbation size

### ISSUE THREAD

**Issue by spencerwooo** [bethgelab/foolbox#532]
I'm finding a way to limit the perturbation size generated among different attacks. After digging into the source code, I found that the parameter `threshold`:

> ... only influences early stopping of the attack; the returned adversarial does not necessarily have smaller perturbation size than this threshold.

If so, if I want to limit the size of the perturbation generated with different attacks, does that mean that I will need to manually check if the perturbation size for each generated adversary is beyond the limitation? What would be the proper way to set a limit for running attacks? (A simple code demo would be best!) Thanks!

**Comment by jonasrauber** [comment]
Short answer: You should probably just upgrade to Foolbox 3 to get everything you want (specifying epsilons and getting adversarials that fulfil the epsilon constraint).

Longer answer: The reason for the minimization approach in Foolbox 1 & 2 is that it's generally bad to only look at an individual threshold, and by returning the minimal adversarial perturbation, it's easy to compute robust accuracy / attack success rate for many different thresholds.

**Comment by spencerwooo** [comment]
Thanks for the prompt reply!

> Short answer: You should probably just upgrade to Foolbox 3...

I couldn't help but notice that a lot of the attacks that are available in Foolbox 2 are currently not available (or not documented) in Foolbox 3, for instance: the `MomentumIterativeAttack`, the `SaliencyMapAttack` and some of the decision-based attacks like the `HopSkipJumpAttack`. So I can't make the switch yet. I think I'm going to stick to Foolbox 2 for the time being.

---

Also, two follow up questions: 

1. Do specifying the `distance=xxx` when initializing the attack affect the returned adversary? More specifically: is it correct for me to calculate the L2 norm distance with `_l2 = np.linalg.norm(perturb.flatten(), 2)` (where the `perturb = adv - img`) while leaving the default `distance=MeanSquaredDistance` unchanged?
2. Is there a way to fetch the L2 norm distance directly with `adv.distance.value` in Foolbox 2? (Because I believe `foolbox.distances` doesn't support L2 norm in Foolbox 2.)

**Comment by spencerwooo** [comment]
OK...please ignore the last two questions. Turns out I misunderstood the way attacks work when specifying different distance norms, my mistake. 🤦‍

I have a final question:

> You should probably just upgrade to Foolbox 3 to get everything you want (specifying epsilons and getting adversarials that fulfil the epsilon constraint).

Could you please elaborate a bit more on how to fulfill a specific constraint, particularly, on attacks with a minimization approach like the Carlini & Wagner attack?

**Comment by spencerwooo** [comment]
I don't know if I'm doing something wrong, but **with Foolbox 3.0** I was able to set a epsilon constraint with attacks like `LinfBasicIterativeAttack`, where I get a clean line when I calculate the distances after the attack completes. However I failed to set constraints for attacks like `LinfDeepFoolAttack`.

![image](https://user-images.githubusercontent.com/32114380/79126715-0e514500-7dd3-11ea-8bb6-9369d25a3b41.png)

> Left: `LinfBasicIterativeAttack` | Right: `LinfDeepFoolAttack`

Is this supposed to happen?

What I basically did was initialize a PyTorch model:

```python
fmodel = PyTorchModel(model, bounds=(0, 1), preprocessing=preprocessing)
```

Then perform the attack with a specific epsilon:

```python
attack = fa.LinfBasicIterativeAttack()
# attack = fa.LinfDeepFoolAttack()
eps = [4 / 255]

# perform attack
adv, _, _ = attack(fmodel, image, label, epsilons=eps)

# calculate linf distance
perturb = image - adv
_linf = norm(perturb.flatten(), np.inf)

# do some plotting ...
```

I can provide a minimal working example if needed. Thanks for all the help!

**Comment by zimmerrol** [comment]
Since the `LinfDeepFoolAttack` is a `MinimizationAttack` meaning that it will always (if possible) return an adversarial example and during the attack's iterations only the magnitude of the perturbation will be reduced, the (raw) output of this attack is not always limited to the same epsilon value. However, all attacks in foolbox return 3 values: the raw perturbed images, a clipped version of these images and whether the attack was succesful. In most cases you should only use the second value and not the unclipped value. 

In you code example, this means modifying the attack line with:
```
_, adv, _ = attack(fmodel, image, label, epsilons=eps)
```
