### ISSUE TITLE
Missing requirement: requests

### ISSUE THREAD

**Issue by zimmerrol** [bethgelab/foolbox#534]
The `weight_fetcher.py` file requires the `requests` library, which is not added as a dependency in the current pip package. Therefore, scripts might crash when they try to import the model zoo when the user has not installed the `requests` library manually before.
I think it's good that the requests library is not added as a dependency for the entire library, as it might not be used that often. However, maybe we can think about try...catching the import of the requests library and wrapping it with a more user-friendly message informing them, that they need to install this library on their own. What do you think of this @jonasrauber ?

**Comment by dpaiton** [comment]
I had to install requests library after importing eagerpy on python 3.6.7. I'm not sure if this came from weight_fetcher.py or not, though.

**Comment by jonasrauber** [comment]
@zimmerrol Fully agree, let's not add it as an install-dependency, but let's inform users rather than throwing the error at them.

**Comment by jonasrauber** [comment]
This was closed by #572
