### ISSUE TITLE
Targeted Gradient Attacks

### ISSUE THREAD

**Issue by isaac-dunn** [bethgelab/foolbox#538]
It seems that gradient-based attacks such as PGD only support the Misclassification criterion at the moment. Is support for the TargetedMisclassification criterion available or planned soon?

Otherwise, I'm really excited about foolbox v3 - thank you!

**Comment by jonasrauber** [comment]
We should indeed change that. No ETA though. Contributions are welcome.

**Comment by Hrushikesh-github** [comment]
Any updates regarding targeted misclassification?

**Comment by jonasrauber** [comment]
Targeted PGD has been implemented in #588. We forgot to update this issue, sorry.
