### ISSUE TITLE
Pointwise Attack

### ISSUE THREAD

**Issue by pratyushmaini** [bethgelab/foolbox#540]
Has the support for Pointwise Attack been removed? It was present till v 2.4 it seems. 
(L. Schott, J. Rauber, M. Bethge, W. Brendel: “Towards the first adversarially robust neural network model on MNIST”, ICLR (2019) https://arxiv.org/abs/1805.09190)

**Comment by jonasrauber** [comment]
No, but we have not yet had time to port it to Foolbox 3 (i.e. it will come back). Let's keep this open until we have added to Foolbox 3 as well.
