### ISSUE TITLE
The pytorch example code cannot execute successfully with cuda device

### ISSUE THREAD

**Issue by Buhua-Liu** [bethgelab/foolbox#542]
The env is pytorch==1.4.0, foolbox==3.0.0b1, python==3.6;
When I run the [pytorch example code](https://foolbox.jonasrauber.de/guide/examples.html) with cuda==10.1 available, it shows 
```
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target' in call to _thnn_nll_loss_forward
```
So I delete the `ep.astentors()` wrapper, and add 
```
labels = labels.dtype(torch.LongTensor)
```
I wonder whether EagerPy or Foolbox does not support GPU acceleration since I have yet look into the source code.

**Comment by jonasrauber** [comment]
Foolbox and EagerPy fully support GPU.
I think the problem is somewhere. I assume you found it?

**Comment by Buhua-Liu** [comment]
The `ep.astensors()` still does not work for me, so I instead use 
```
labels = labels.dtype(torch.cuda.LongTensor)
```
to deal with the TypeError.

**Comment by FernandoZhuang** [comment]
if variable `labels` was int, then `labels` should be converted to long tensor. `ep.astensor(labels.long())` works for me.
