### ISSUE TITLE
Faster the attacking speed

### ISSUE THREAD

**Issue by yitao416** [bethgelab/foolbox#546]
Hello,

Any suggestions on speeding up the attack? such as use numba to wrap the attack class? 

Thanks!

**Comment by wielandbrendel** [comment]
Which attack are you referring to? All the heavy lifting now runs on the GPU so Numba will usually not be much of a help.

**Comment by yitao416** [comment]
The Carlini & Wagner L2 Attack is taking unexpected long time to compute. I guess it is just because of the nature of that attack algorithm. 

I have tried many accelerating packages, but fail to achieve much improvement. 

I guess the Cython could be the solution, but it would be too complicated to write a neural net. 

Thanks for your feedback.

**Comment by jonasrauber** [comment]
The CW attack just uses a lot of iterations so it is inherently slow. If you see a substantial performance difference between the Foolbox implementation and another CW implementation, that would be worth looking into. Right now, I assume it's as slow as other implementations.
