### ISSUE TITLE
What does the second element in the returned tuple mean?

### ISSUE THREAD

**Issue by shwangtangjun** [bethgelab/foolbox#555]
In the minimum working example, I see that the return data of attack is a tuple, with 3 elements.

`attack = LinfPGD()`
`epsilons = [0.0, 0.001, 0.01, 0.03, 0.1, 0.3, 0.5, 1.0]`
`advs, _ , success = attack(fmodel, images, labels, epsilons=epsilons)`

However, I print those elements, and find that "advs" and "_" are exactly the same. So I wonder what's the meaning of returning two same elements?

Plus, I have searched in the doc, and can't find a single description on what "_" means.

**Comment by AbnerHqC** [comment]
Got same question...

**Comment by wielandbrendel** [comment]
The attack always returns the raw output of the attacks (first argument) and the output clipped to the specified epsilon (second argument) in case the attack does not do this automatically. The '_' is just a standard [Python symbol for unused variables](https://www.datacamp.com/community/tutorials/role-underscore-python#IV).
