### ISSUE TITLE
Please add HopSkipJump Attack

### ISSUE THREAD

**Issue by agpeshal** [bethgelab/foolbox#558]
A new black-box attack has been published by Chen et al. [https://arxiv.org/pdf/1904.02144.pdf](https://arxiv.org/pdf/1904.02144.pdf). Kindly provide support.

**Comment by shudongzhang** [comment]
https://github.com/bethgelab/foolbox/blob/v2/foolbox/attacks/hop_skip_jump_attack.py

**Comment by agpeshal** [comment]
@shudongzhang Thanks you so much!

**Comment by agpeshal** [comment]
Why has it been removed from the latest version? Is there a way to apply HSJA with the current version?

**Comment by jonasrauber** [comment]
It needs to be updated for Foolbox 3; so far that hasn't been done

**Comment by jonasrauber** [comment]
That requires some refactoring of the attack due to the various improvements in Foolbox. Contributions are welcome.

**Comment by zimmerrol** [comment]
This issue was resolved, see [here](url)https://github.com/bethgelab/foolbox/blob/master/foolbox/attacks/hop_skip_jump.py].
