### ISSUE TITLE
importing tensorflow 1.0 models in v3

### ISSUE THREAD

**Issue by stanleybak** [bethgelab/foolbox#560]
Is it possible to import tensorflow 1.0 models in the newest version? There used to be two interfaces in v2:

```
model = foolbox.models.TensorFlowModel(images, logits, bounds=(0, 255))  # Use this for TensorFlow 1.0
model = foolbox.models.TensorFlowEagerModel(model, bounds=(0, 255))  # Use this for TensorFlow 2.0
```

But in v3 I no longer see the way to import tensorflow 1.0 models.

**Comment by jonasrauber** [comment]
Indeed, using graph-based TensorFlow models got a bit more complex in Foolbox 3. That's because Foolbox 3 requires eager execution. The way to go is to wrap the graph-based model such that it can be used with eager execution (TF2). Unfortunately I can't provide any code right now because I haven't tried it myself, but afaik people have successfully done this. @wielandbrendel, do you have some code for this?

I think is something we should add to the docs once we figured it out.

**Comment by wielandbrendel** [comment]
@jonasrauber This is highly non-trivial and I am not sure it is even possible, in an automated way, to turn a graph-based model into an eager execution model. At least that was my conclusion the last time I tried.

**Comment by jonasrauber** [comment]
I see. I was somehow hoping some graph-based code could more or less without any changes be embedded in an eager function (the other way round I think is possible using something like `py_func` but for eager code; pretty sure I saw that before).

@stanleybak Let's leave this open until someone can say for sure or figures it out. Right now we don't have a solution.

**Comment by stanleybak** [comment]
My application actually has networks starting in the [ONNX](https://github.com/onnx/onnx) format, so Tensorflow 2.0 is not really essential for what I'm trying to do. 

ONNX is not supported by foolbox v3 directly (as far as I know), but do you guys know if I could convert from ONNX to any of the input formats foolbox v3 supports? I've only so far succeeded in converting from ONNX to tensorflow 1.0, which is why I asked the question here.

**Comment by jonasrauber** [comment]
PyTorch has support for ONNX: https://pytorch.org/docs/stable/onnx.html
TensorFlow 2 and JAX should also be able to load a ONNX model.

**Comment by stanleybak** [comment]
support for onnx often means they can export to onnx, rather than import from onnx (for example, in the pytorch case).

**Comment by jonasrauber** [comment]
@stanleybak Here is a JAX example where they load an ONNX model: https://github.com/google/jax/blob/master/examples/onnx2xla.py

**Comment by stanleybak** [comment]
This is great thank you. There are only 7 ONNX ops that it supports, but it's a good starting point.
