### ISSUE TITLE
Clipping in GenAttack doesn't seem right

### ISSUE THREAD

**Issue by superctj** [bethgelab/foolbox#564]
Adversarial images generated by the black box attack GenAttack do not have a valid pixel range. Tracing back to the source code, I think [the clipping](https://github.com/bethgelab/foolbox/blob/94df1e7af28947fca190f25279475468d45ac00d/foolbox/attacks/gen_attack.py#L70) is very suspectable.

**Comment by jonasrauber** [comment]
@zimmerrol Could you have a look, I think you ported this to Foolbox 3?
