### ISSUE TITLE
I want to attack my own model training by tensorflow2.0

### ISSUE THREAD

**Issue by Madanfeng** [bethgelab/foolbox#566]
I want to attack my own model training by tensorflow2.0, how do I modify the code? I try to modify examples/tensorflow_resnet50.py, here is my code, but have bug.
`# instantiate a model
    # model = tf.keras.applications.ResNet50(weights="imagenet")
    
    model = tf.keras.models.load_model('/Users/madanfeng/Downloads/seqing/model/model.stage4.04-0.9697.v2_320_tf2.hdf5')
    pre = dict(flip_axis=-1, mean=[104.0, 116.0, 123.0])  # RGB to BGR
    fmodel = TensorFlowModel(model, bounds=(0, 255), preprocessing=pre)
    # get data and test the model
    # wrapping the tensors with ep.astensors is optional, but it allows
    # us to work with EagerPy tensors in the following
    # images, labels = ep.astensors(*samples(fmodel, dataset="imagenet", batchsize=16))

    image = cv.imread('/Users/madanfeng/Downloads/imgs/cec7cf7da3118b9b6902d751b8d3cd70.jpg')
    image = cv.cvtColor(image, cv.COLOR_BGR2RGB)
    image = cv.resize(image, (320, 320))
    image = image / 255.
    
    images = np.zeros([1, 320, 320, 3])
    images[0, :, :, :] = image

    labels = np.zeros([1, 20], dtype=np.float32)
    labels[0, 3] = 1.

    # print(accuracy(fmodel, images, labels))

    # apply the attack
    attack = LinfPGD()
    # attack = L2CarliniWagnerAttack()
    epsilons = [0.0, 0.001, 0.01, 0.03, 0.1, 0.3, 0.5, 1.0]
    advs, _, success = attack(fmodel, images, labels, epsilons=epsilons)`

bug:
Traceback (most recent call last):
  File "/Users/madanfeng/Desktop/test/ADV/foolbox/examples/tensorflow_resnet50.py", line 39, in <module>
    advs, _, success = attack(fmodel, images, labels, epsilons=epsilons)
  File "/Users/madanfeng/Desktop/test/ADV/foolbox/foolbox/attacks/base.py", line 279, in __call__
    xp = self.run(model, x, criterion, epsilon=epsilon, **kwargs)
  File "/Users/madanfeng/Desktop/test/ADV/foolbox/foolbox/attacks/gradient_descent_base.py", line 88, in run
    _, gradients = self.value_and_grad(loss_fn, x)
  File "/Users/madanfeng/Desktop/test/ADV/foolbox/foolbox/attacks/gradient_descent_base.py", line 52, in value_and_grad
    return ep.value_and_grad(loss_fn, x)
  File "/Users/madanfeng/opt/anaconda3/envs/foolbox/lib/python3.7/site-packages/eagerpy/framework.py", line 346, in value_and_grad
    return t.value_and_grad(f, *args, **kwargs)
  File "/Users/madanfeng/opt/anaconda3/envs/foolbox/lib/python3.7/site-packages/eagerpy/tensor/tensor.py", line 537, in value_and_grad
    return self._value_and_grad_fn(f, has_aux=False)(self, *args, **kwargs)
  File "/Users/madanfeng/opt/anaconda3/envs/foolbox/lib/python3.7/site-packages/eagerpy/tensor/numpy.py", line 363, in _value_and_grad_fn
    raise NotImplementedError  # pragma: no cover
NotImplementedError

**Comment by jonasrauber** [comment]
It seems you are passing NumPy arrays to the attack, but it expects TensorFlow tensors.

Reminder to self: we should catch this and point people in the right direction; seems to be a common problem, probably because Foolbox 1 and 2 required NumPy arrays and Foolbox 3 now requires native tensors.

**Comment by tylerdoll** [comment]
I was able to solve this by doing what @jonasrauber suggested. Simply pass your numpy arrays to tf.convert_to_tensor().

For example:
```python
import numpy as np
import tensorflow as tf

input = np.array(...)
tf_input = tf.convert_to_tensor(input) # pass this to your attack method
```
