### ISSUE TITLE
support batch_predictions

### ISSUE THREAD

**Issue by AngusG** [bethgelab/foolbox#57]
Creating this issue for tracking progress and ideas related to adding support for batch_predictions, templated out in https://github.com/bethgelab/foolbox/blob/master/foolbox/models/base.py#L69

**Comment by wielandbrendel** [comment]
Hey @AngusG there might be a misunderstanding: the method batch_predictions is fully implemented in each model (e.g. for Keras in https://github.com/bethgelab/foolbox/blob/master/foolbox/models/keras.py#L112).

**Comment by AngusG** [comment]
Yep I misunderstood. Closing now.
