### ISSUE TITLE
problem attacking my own model

### ISSUE THREAD

**Issue by gzyon** [bethgelab/foolbox#575]
i want to attack a model that is created using keras tensorflow, but it does not work.

if i convert it to a foolbox model using the preprocessing provided in the example, the accuracy is 0 and the attack does not work (code will run but no difference on image prediction)

if i use the model without converting it to a foolbox model, it gives the error "AttributeError: 'Sequential' object has no attribute 'bounds'"

my images and labels are of the same type as that in the example as well (Tensorflow tensors)

how should i import and preprocess my model such that the attack is successful?

**Comment by jonasrauber** [comment]
Well, you need to specify the right preprocessing for your model. And then use the non-preprocessed inputs (because the preprocessing is now done by the model). And then you should get the same accuracy as your original model.

Only once that's the case, you should start attacking your model and then everything will work.

**Comment by miyucloud** [comment]
> Well, you need to specify the right preprocessing for your model. And then use the non-preprocessed inputs (because the preprocessing is now done by the model). And then you should get the same accuracy as your original model.
> 
> Only once that's the case, you should start attacking your model and then everything will work.

can i ask if this is a form of preprocessing? 

`image = exposure.equalize_adapthist(image, clip_limit=0.1) `

and is this the same as bounds=(0, 255) as specified in the example?

```
trainX = trainX.astype("float32") / 255.0
testX = testX.astype("float32") / 255.0
```

lastly, do i also need to specify the labels processing? 

```
trainY = to_categorical(trainY, numLabels)
testY = to_categorical(testY, numLabels)
```

sorry for asking so many questions, i only started this recently and am quite new to machine learning 

thanks for the answer!

**Comment by jonasrauber** [comment]
If you divide the inputs by 255, they are probably between 0 and 1 and assuming that's what your model expects, then you should specify `(0, 1)` as the bounds. But it's really hard to say for sure with the small amount of information available.
The labels you pass to Foolbox should be a 1-dimensional tensor with the class IDs.
P.S.: have you looked at the tutorial?

**Comment by miyucloud** [comment]
> If you divide the inputs by 255, they are probably between 0 and 1 and assuming that's what your model expects, then you should specify `(0, 1)` as the bounds. But it's really hard to say for sure with the small amount of information available.
> The labels you pass to Foolbox should be a 1-dimensional tensor with the class IDs.
> P.S.: have you looked at the tutorial?

i have looked at the tutorial actually. but despite being able to get the correct inputs, i cant seem to get the preprocessing right at all. would it be possible to leave the model preprocessing as None, and preprocess the image myself before feeding it into the foolbox model?
