### ISSUE TITLE
Change of EAD attack causes problems

### ISSUE THREAD

**Issue by zdhNarsil** [bethgelab/foolbox#579]
When I use foolbox 3.0.4, I can get non-trival results (ie. >0% but very close to 100%) from EAD attack for adv-trained small cnn on mnist. The cnn is trained with linf, l2, l1 pgd attacks all together.

In the recent [update](https://github.com/bethgelab/foolbox/commit/08fae045648c07352c18c0ae1c225b5c288aa805#diff-031fe5fea76e5c0eddd4e9d9edd21a0c) of foolbox, the code of EAD changes one single line with previous version.

And when I update foolbox to 3.1.1 and change nothing else, the accuracy **drop to 0%** for EAD attack on my previous code.
When I re-install foolbox 3.0.4, things get back agian.

**Comment by jonasrauber** [comment]
Isn’t this good? I mean the attack’s purpose is to reduce the accuracy, no?

**Comment by jonasrauber** [comment]
@zimmerrol can you double check the change you made

**Comment by zdhNarsil** [comment]
> Isn’t this good? I mean the attack’s purpose is to reduce the accuracy, no?

But the single change seems to have the same meaning as before, which is really confusing..

**Comment by zimmerrol** [comment]
@zdhNarsil In the old version of EAD the best adversarial found so far was updated with `x_k` if `y_k` is adversarial. This is obviously a bug and it should be `x_k` in both cases. Please check the algorithm in the original paper, if you think there is still a mistake.. The longer the attack runs, the closer `x_k` and `y_k` become and, thus, sometimes there was no clear difference noticeable when running the attack for longer times against a model.
