### ISSUE TITLE
[JOSS Review] State of the field

### ISSUE THREAD

**Issue by ethanwharris** [bethgelab/foolbox#581]
Hi, I'm reviewing the Foolbox native paper on JOSS ([openjournals/joss-reviews/issues/2607](https://github.com/openjournals/joss-reviews/issues/2607)). In order to satisfy the [state of the field check in the software paper review criteria](https://joss.readthedocs.io/en/latest/review_checklist.html#software-paper), it would be good if you could include some discussion of other libraries that are focussed on adversarial robustness research. The two other commonly-used packages that I know of (may not be an exhaustive list) and would be good to briefly compare to are [CleverHans](https://github.com/tensorflow/cleverhans) and [AdverTorch](https://github.com/BorealisAI/advertorch).

**Comment by jonasrauber** [comment]
Hi @ethanwharris, thanks for taking the time to review Foolbox Native. I am currently on holidays and will get back to you with a more detailed  answer next week. The main difference is that we support multiple frameworks, not just either PyTorch (AdverTorch) or TensorFlow (Cleverhans).

**Comment by jonasrauber** [comment]
I added a paragraph comparing Foolbox Native to CleverHans, AdverTorch, and ART (https://github.com/bethgelab/foolbox/commit/8b500251f4b741da09a6959c39aa8af1ce038f13) that should make the difference clear.
