### ISSUE TITLE
[JOSS Review] Performance

### ISSUE THREAD

**Issue by GregaVrbancic** [bethgelab/foolbox#587]
Hi @jonasrauber, I summary of the paper and also in the readme is mentioned that the Foolbox was rewritten from scratch to achieve native performance. It would be interesting if you could provide us with some performance comparison (maybe in a form of chart or table) between the current version and the previous one.

**Comment by jonasrauber** [comment]
Good point @GregaVrbancic. I have now added a simple performance comparison to the repository: https://github.com/bethgelab/foolbox/tree/master/performance
