### ISSUE TITLE
TypeError: Can not convert a NoneType into a Tensor or Operation

### ISSUE THREAD

**Issue by shenqixiaojiang** [bethgelab/foolbox#59]
When I used the keras model to get the adversarial examples.  
There was an error happened on the line 96 of the file 'keras.py'.
The following is the details:

   fmodel = foolbox.models.KerasModel(kmodel, bounds=(0, 255)) #, preprocessing=preprocessing)
    File "/usr/lib/python2.7/site-packages/foolbox/models/keras.py", line 96, in __init__
    [predictions, grad])

TypeError: Can not convert a NoneType into a Tensor or Operation.

So who  can give me some advice on the matter?
Thank you very much.

**Comment by wielandbrendel** [comment]
Could you post a minimal example that reproduces the error (e.g. based on the keras example in the readme)?

**Comment by jonasrauber** [comment]
And could you please specify which Keras backend you use.

**Comment by shenqixiaojiang** [comment]
@jonasrauber @wielandbrendel  The Tensorflow backend was used whose version is 1.2.0 and my version of Python is 2.7
     The example is the following:

import foolbox
import keras
import numpy
from keras.applications.resnet50 import ResNet50

# instantiate model
keras.backend.set_learning_phase(0)
kmodel = ResNet50(weights='imagenet')
preprocessing = (numpy.array([104, 116, 123]), 1)
fmodel = foolbox.models.KerasModel(kmodel, bounds=(0, 255), preprocessing=preprocessing)

Which is showed on the home page of foolbox.

**Comment by shenqixiaojiang** [comment]
@wielandbrendel    I don't know why but it works now. Thanks.

**Comment by gmt710** [comment]
@wielandbrendel 
Thanks.I solved the problem for the latest version by updating foolbox.
