### ISSUE TITLE
Wrong tensor types in PyTorch examples

### ISSUE THREAD

**Issue by benjaminsg** [bethgelab/foolbox#593]
Getting "Expected object of scalar type Long but got scalar type Int for argument #2 'target' in call to _thnn_nll_loss_forward" when running single_attack_pytorch_resnet18.py immediately after install. Reverted my PyTorch version to 1.4.0 and still getting the same issue.

Tried to look into tensor cast typing solutions and found no working methods. Running on Windows through Anaconda environment. Anyone else experience this issue?

**Comment by zimmerrol** [comment]
This should be fixed by now.
