### ISSUE TITLE
Is it possible to create an adversarial example with a spatio-temporal gradient?

### ISSUE THREAD

**Issue by giacomop96** [bethgelab/foolbox#594]
Hi, I need to create an adversarial attack for an SNN, trained on IBM DVS-Gestures dataset. The dataset is composed of data registered with a DVS camera that are represented as pulses. So they have an additional temporal dimension. When I was trying to attack it with the PGD attack, it return an error saying that it can only work with 2D gradients. Is it possible to do it also with 3D  or not?
Thanks

**Comment by zimmerrol** [comment]
If you don't want to enforce any constraints on the temporal dimension (i.e. temporal consistency of the perturbation) could wrap your original model in a model that receives a `2D` tensor and reshapes it to a `3D` tensor, feeds it to your original model and returns the original output. That way, foolbox will only process `2D` data (i.e. "images") you won't see the error message you mentioned above.
