### ISSUE TITLE
[DDNAttack] Cosine annealing formula

### ISSUE THREAD

**Issue by maurapintor** [bethgelab/foolbox#595]
Referring to the cosine annealing formula: 

![image](https://user-images.githubusercontent.com/23276849/96274551-eb495d00-0fd0-11eb-940c-e8d02f6c1326.png)

It seems that the one used in the DDN attack [here](https://github.com/bethgelab/foolbox/blob/master/foolbox/attacks/ddn.py#L116) is producing a different result.

The algorithm is now using the stepsize at the current step instead of the maximum stepsize that should be used in the formula.

# Steps to reproduce

```python
import torch
from torch import optim
from torch.optim.lr_scheduler import CosineAnnealingLR

num_steps = 100
max_stepsize = 1.0
min_stepsize = 0.01
stepsize_wrong = 1.0  # initial stepsize for the wrong formula
optimizer = optim.SGD([torch.tensor(10)], lr=1)
scheduler = CosineAnnealingLR(optimizer, T_max=num_steps, eta_min=0.01)

stepsizes, wrong_stepsizes, torch_stepsizes = [], [], []
for i in range(num_steps):

    # correct implementation
    stepsize = min_stepsize + 0.5 * (max_stepsize - min_stepsize)*(1 + math.cos(i/num_steps*math.pi))

    # current version
    stepsize_wrong = min_stepsize + 0.5 * (stepsize_wrong - min_stepsize)*(1 + math.cos(i/num_steps*math.pi))
    
    # torch cosine annealing scheduler
    torch_stepsize = scheduler.get_last_lr()
    scheduler.step()

    stepsizes.append(stepsize)
    wrong_stepsizes.append(stepsize_wrong)
    torch_stepsizes.append(torch_stepsize[0])

print(stepsizes)
print(torch_stepsizes)  # is equal to the previous
print(wrong_stepsizes)  # different!
```

# Fix

```python
max_stepsize = 1.0
...
for i in range(self.steps):
    stepsize = (
                0.01 + (max_stepsize - 0.01) * (1 + math.cos(math.pi * i / self.steps)) / 2
            )
    ...
```

# Plot

![image](https://user-images.githubusercontent.com/23276849/96274039-58a8be00-0fd0-11eb-97ec-b9fa10dd3e7d.png)

# Useful refs

[https://pytorch.org/docs/stable/optim.html#torch.optim.lr_scheduler.CosineAnnealingLR](https://pytorch.org/docs/stable/optim.html#torch.optim.lr_scheduler.CosineAnnealingLR)

**Comment by jonasrauber** [comment]
Thanks Maura!

**Comment by jonasrauber** [comment]
Thanks Maura!
@zimmerrol could you review the PR?

**Comment by zimmerrol** [comment]
@jonasrauber LGTM.
