### ISSUE TITLE
LBFGS and SaliencyMapAttack are lower-bounded by GradientAttack

### ISSUE THREAD

**Issue by wielandbrendel** [bethgelab/foolbox#60]
Right now LBFGS and SaliencyMapAttack use the GradientAttack to initialise the best target class in a misclassification setting. Due to the internal optimisation of the adversarial object it can happen that the best adversarial is actually found by the GradientAttack and not by LBFGS or SaliencyMap. We should reset the adversarial object to avoid this confound. I am currently testing a PR.

**Comment by jonasrauber** [comment]
Can you explain why you think that this is problematic?
We are to some extent free to define these attacks... e.g. LBFGSAttack := GradientAttack + LBFGS

**Comment by wielandbrendel** [comment]
Sure, but the comparison is then screwed and bugs in LBFGS are harder to find (if you screw up the LBFGS implementation you will not get a failure but you will simply get the result of the GradientAttack). Right now LBFGS cannot get worse then GradientAttack, but it turns out that LBFGS and the SaliencyMapAttack actually perform worse then GradientAttack for many samples. This is something we want to report in the Benchmark.

**Comment by jonasrauber** [comment]
Agreed

**Comment by jonasrauber** [comment]
@wielandbrendel can this be closed?
