### ISSUE TITLE
foolbox automatically consumes GPU memory

### ISSUE THREAD

**Issue by giangnguyen2412** [bethgelab/foolbox#600]
Even when my model is set to CPU, when I define fmodel, it will stll take my GPU memory.
For example, Im using TitanX ~ 14GB RAM, running a batch of 100 images at size 224x224 will cause a failure

**Comment by jonasrauber** [comment]
Foolbox's `PyTorchModel` defaults to GPU if one is available. You can override that by passing `device="cpu"` or `device=torch.device("cpu")` explicitly to `PyTorchModel`.
