### ISSUE TITLE
Why is TargetedMisclassification is not allowed in FGSM?

### ISSUE THREAD

**Issue by hasanferit** [bethgelab/foolbox#607]
As far as I understand, targeted misclassification is not yet implemented in FGSM (see [here](https://github.com/bethgelab/foolbox/blob/master/foolbox/attacks/fast_gradient_method.py#L90 ). Do you plan to add it soon?  Also, is contributions on this welcomed?

**Comment by jonasrauber** [comment]
I don't think FGSM is suitable for targeted misclassification. Actually, FGSM should probably not be used for anything except prototyping or sanity checks.

Contributions in general are of course highly welcome.

**Comment by hasanferit** [comment]
I thought a targeted version can be derived easily, but yes, you are right, it is a very weak attack in general.
