### ISSUE TITLE
Can you provide targeted and untargeted attack example of boundary attack?

### ISSUE THREAD

**Issue by machanic** [bethgelab/foolbox#609]
Boundary attack is a famous hard-label attack.
1. Can you provide targeted and untargeted attack example of boundary attack?
2. I want to count query and the generated sample's distortion pair during the attack process. How to modify the code to support statistics during the attack process.

**Comment by machanic** [comment]
Can you provide examples about the above two questions?

**Comment by psteinb** [comment]
We are also using the boundary attack. Not sure what you mean by targeted or untargeted fashion?
