### ISSUE TITLE
AttributeError: module 'foolbox.models' has no attribute 'KerasModel'

### ISSUE THREAD

**Issue by AlphabugX** [bethgelab/foolbox#611]
/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/backend.py:434: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
  warnings.warn('`tf.keras.backend.set_learning_phase` is deprecated and '
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/alphabug/00-dbappsecurity/Ai/test5.py", line 98, in <module>
    fmodel = foolbox.models.KerasModel(inference_model, bounds=(0, 1))
AttributeError: module 'foolbox.models' has no attribute 'KerasModel'

**Comment by NMTech0x90** [comment]
tensorflow==2.4.0
Keras==2.4.3
foolbox==3.2.1
Python==3.8.5

**Comment by NMTech0x90** [comment]
help~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Lior5** [comment]
I think KerasModel no longer exists in foolbox 3.2.1 https://foolbox.readthedocs.io/en/stable/modules/models.html
I know it's a thing in foolbox 2.4.0 though: https://foolbox.readthedocs.io/en/v2.4.0/modules/models.html#foolbox.models.KerasModel

You might be able to easily swap it out for a TensorFlowModel though.

**Comment by zimmerrol** [comment]
@Lior5 is correct: please use the `TensorFlowModel` class for wrapping keras models in foolbox 3.X.
