### ISSUE TITLE
Nondeterministic behavior with Keras Preprocessing Layers

### ISSUE THREAD

**Issue by tylerdoll** [bethgelab/foolbox#622]
When using models with preprocessing layers such as image augmentations, the classification results can differ due to the way inference is called.

For example this line here:
https://github.com/bethgelab/foolbox/blob/92af8673ee957e5af1f9ad5f3abb474c63f93397/foolbox/models/base.py#L102

Here `_model()`  is not called with training=False as described here in Tensorflow. https://github.com/tensorflow/tensorflow/blob/85c8b2a817f95a3e979ecd1ed95bff1dc1335cff/tensorflow/python/keras/engine/training.py#L1513

To reproduce I ran a test with the following code:
```python
import numpy as np
from tensorflow.keras.models import load_model

model_paths = [...]
img = np.array(...)
att_img = np.array(...)

models = []
for model in model_paths:
    print(model)
    models.append(load_model(model))

for model in models:
    print(np.argmax(model(img[None, :])), np.argmax(model(img[None, :], training=False)), np.argmax(model.predict(img[None, :])))
    print(np.argmax(model(att_img[None, :])), np.argmax(model(att_img[None, :], training=False)), np.argmax(model.predict(att_img[None, :])))

```
Output:
3 3 3
3 3 3
3 3 3
3 3 3
3 3 3
**2 3 3
2 3 3**
3 3 3

Tensorflow v2.3.0
Foolbox v3.3.0

**Comment by zimmerrol** [comment]
@tylerdoll Thanks for opening this issue. Can you please explain what the expected/desired output of the code example above should be?
