### ISSUE TITLE
Top-k misclassification on ImageNet

### ISSUE THREAD

**Issue by ines21** [bethgelab/foolbox#626]
Running an untargeted attack on an ImageNet classifier results in a church being classified as a monastery instead. Do you maybe have a suggestion or a workaround to introduce top-k misclassification?

**Comment by jonasrauber** [comment]
We did support top-k misclassification in Foolbox 1 and 2: https://github.com/bethgelab/foolbox/blob/v2.4.0/foolbox/criteria.py#L209
It has not yet been ported to Foolbox 3. Adding the criterion should be easy, making sure it works with certain attacks probably requires some more testing.

**Comment by zimmerrol** [comment]
@ines21 Is there an update from your side?
