### ISSUE TITLE
Computing the deltas the right way for DeepFool (L2)

### ISSUE THREAD

**Issue by sayakpaul** [bethgelab/foolbox#632]
Referring to this [Colab Notebook](https://colab.research.google.com/github/jonasrauber/foolbox-native-tutorial/blob/master/foolbox-native-tutorial.ipynb).

I have just replaced the L_Inf DeepFool attack with L2. Now, I am trying to compute the deltas and plot them. Is the following the right way to do it? 

```
fb.plot.images(raw - images, n=4, bounds=(-0.1, 0.1), scale=4.)
```

Please note the following:

The model I am testing this with (it's an ImageNet-pretrained model) takes inputs in the range of [-1, 1] and therefore the bounds have been set to (-1, 1).

Many thanks.

**Comment by zimmerrol** [comment]
You should ideall use the `clipped` variable instead of `raw` (the former contains the adversarials clipped to the epsilon ball, if you use a norm-bounded adversarial attack, the latter is not clipped and, thus, might have perturbations with magnitude larger than epsilon).

**Comment by sayakpaul** [comment]
Worth clearing it up either in the Colab Notebook or in the documentation. It's quite a significant detail that can be easily missed out.
