### ISSUE TITLE
How to find number of times model was queried for black box attacks ?

### ISSUE THREAD

**Issue by amir1m** [bethgelab/foolbox#638]
Hello,
For Black box evasion attacks such as ZOO, SimBA, Boundary, etc.,  is there a way to log/find number of times model was queried?

Thanks

**Comment by zimmerrol** [comment]
The easiest way to do this in a reliable way would be to modify your model definition such that in the `forward` function of the model (assuming you use a `PyTorchModel`) a counter is increased logging how often the forward pass was executed. Foolbox itself does not offer a general API for logging the number of queries that works for all attacks (as far as I remember).
