### ISSUE TITLE
Where is Saliency Map Attack method in foolbox version 3 ???

### ISSUE THREAD

**Issue by TheBloodthirster** [bethgelab/foolbox#646]
I saw the issue https://github.com/bethgelab/foolbox/issues/252

which is say JSMA in foolbox in named Saliency Map Attack?

But I can't anything about key word Saliency in document?

And I find this method is defined in version 2.4.0. 

Could anyone tell what's gong on ? How to use JSMA in version 3?

**Comment by jangop** [comment]
Duplicate of #645
