### ISSUE TITLE
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target' in call to _thnn_nll_loss_forward

### ISSUE THREAD

**Issue by zgkzgk** [bethgelab/foolbox#647]
在pycharm中运行single_attack_pytorch_resnet18.py时报错：
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target' in call to _thnn_nll_loss_forward

**Comment by congwang1985** [comment]
same problem here as well

**Comment by benrenzhu** [comment]
> 在pycharm中运行single_attack_pytorch_resnet18.py时报错： RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target' in call to _thnn_nll_loss_forward
加一句
`labels = labels.astype(torch.long)`

**Comment by jangop** [comment]
This does not appear to be a bug in Foolbox. Without more information, I suggest this issue gets closed.
