### ISSUE TITLE
the results are different with "cleverhans"

### ISSUE THREAD

**Issue by WiteBord** [bethgelab/foolbox#650]
I train a pytorch model on cifar10 , and I use fgsm and pgd attack to test my model.
I found the accuracy in these two attack methods are much higher than "cleverhans" and don't know the reason

**Comment by jS5t3r** [comment]
Have you checked the standard parameters? Is the normalization on the right place?  Sharing code would be easier.  There is also the possibility of "Gists".

**Comment by WiteBord** [comment]
I use cifar-10 dataset
cifar10_mean = (0.4914, 0.4822, 0.4465)
cifar10_std = (0.2471, 0.2435, 0.2616)

this is my foolbox code:
``` fmodel=fb.PyTorchModel(generatemodel,bounds=(0,1))
    acc=0
    n=0
    pgd = fb.attacks.PGD()

    for i, data in enumerate(dataloader, 0):
        x, y = data
        x, y = x.cuda(), y.cuda()
        n += y.size(0)

        _, advs, fgsm_success = pgd(fmodel, x,y, epsilons=epsilons)
        acc += y.size(0) - fgsm_success.sum()

    utils.log('eps:{},acc={:4f}'.format(epsilons,acc/n))
```

this is my cleverhans code:
```
    acc = 0
    n = 0

    for i, data in enumerate(dataloader, 0):
        x, y = data
        x, y = x.cuda(), y.cuda()
        n += y.size(0)

        advs = projected_gradient_descent(targetmodel, x, epsilons,epsilons/10,40,np.inf)

        output = targetmodel(advs)
        acc += (output.max(1)[1] == y).sum().item()

    utils.log('eps:{},pgd_acc={:4f}'.format(epsilons, acc / n))
```

**Comment by zimmerrol** [comment]
@WiteBord Can you please check what happens if you run the cleverhans version and our foolbox version with exactly the same attack parameters? If you want to stick to 40 step PGD with a stepsize of eps/40 use this for the foolbox version (assuming `epsilons` is a single float value and not an array/list):
```
pgd = fb.attacks.PGD(abs_stepsize=epsilons/10, steps=40)
...
_, advs, fgsm_success = pgd(fmodel, x,y, epsilons=epsilons)
```

**Comment by WiteBord** [comment]
> @WiteBord Can you please check what happens if you run the cleverhans version and our foolbox version with exactly the same attack parameters? If you want to stick to 40 step PGD with a stepsize of eps/40 use this for the foolbox version (assuming `epsilons` is a single float value and not an array/list):
> 
> ```
> pgd = fb.attacks.PGD(abs_stepsize=epsilons/10, steps=40)
> ...
> _, advs, fgsm_success = pgd(fmodel, x,y, epsilons=epsilons)
> ```

After I check my code, I found the reason is I set wrong bounds. 
Cifar-10 dataset  don't need other processing, so I set bounds from (0,1) to (-255,255).
This operation make the the accuracy 5% lower than "cleverhans" in fgsm and pgd. I think it's normal results.
Thank you for your answer and help.
