### ISSUE TITLE
Is there MIM(Momentum Iterative Mothed) Attack in foolbox v3 ?

### ISSUE THREAD

**Issue by GH1010** [bethgelab/foolbox#655]
Is MIM(Momentum Iterative Mothed) Attack in foolbox v3? I can't find it. Or there is a alternative approach?

**Comment by jangop** [comment]
That is in the works: 1cf17c6a168a3690825fc9e1dd5b9e6dc27b6451.

**Comment by zimmerrol** [comment]
See #656 for updates on this issue.
