### ISSUE TITLE
Increase python version for tests

### ISSUE THREAD

**Issue by zimmerrol** [bethgelab/foolbox#659]
As some time has passed since the unit tests were set up, new python versions came out; thus, it might make sense to test foolbox against one of the latest versions (instead of version 3.6 or 3.7).

**Comment by jangop** [comment]
Personally, I see no reason at all to consider anything below 3.9 at the moment.

**Comment by zimmerrol** [comment]
Yes, I think that is right. I'll update the versions once the work on the unit tests is completed (e.g. #570, #657).

**Comment by zimmerrol** [comment]
Will be closed in #661. Python For the moment we'll have to stay with 3.8 and 3.9 since PyTorch doesn't support 3.10 yet.
