### ISSUE TITLE
Run boundaryattack.py

### ISSUE THREAD

**Issue by nicolem321** [bethgelab/foolbox#684]
Hi!
I am trying to run boundaryattack.py in foolbox/attacks, and it would not let me run unless I do python3 -m foolbox/attacks/boundaryattack.py because of the all the import statements. And it runs into a run time issue because the route is trying to import many things multiple times. But if I just run python3 -m boundaryattack.py when my pwd is in attacks, they say I need to be in the root of the git repo to run. I am kind of stuck. What should I do?

p.s. I am an undergraduate researcher who is trying understand how boundary attacks are implemented.

**Comment by jangop** [comment]
Foolbox is a library and, as such, not meant to be run as an application. This holds for all its parts, specifically its implementation of the boundary attack. Please take a look at [the guide](https://foolbox.jonasrauber.de/) to learn how to get started with Foolbox.

Assuming that you are an undergraduate _student_, you will most likely have access to introductory courses on coding with Python, which should include the use of modules/packages. If you require more information in that regard, I suggest you inquire with fellow students or teaching staff.
