### ISSUE TITLE
Are there any plans to support attacks on TFLite models? 

### ISSUE THREAD

**Issue by fabriceyhc** [bethgelab/foolbox#693]
TFLite is one of the most popular formats for Android and it would be nice to support attacks on them. I'm pretty sure it's not possible to extract gradients from TFLite models, but black-box attacks like [BoundaryAttack](https://github.com/bethgelab/foolbox/blob/master/foolbox/attacks/boundary_attack.py) should still work. 

A potential reference is art's [BlackBoxClassifier](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/e2a7b4ae5a4cefc1b17c3c2b82cdca455736d45f/art/estimators/classification/blackbox.py).

**Comment by zimmerrol** [comment]
Hi, there are no plans to support TFLite directly. However, I believe the most common use case for TFLite is to start with a normal TF model, convert it to a TFLite model and then use it on a mobile device. Thus, in most cases, one in addition to the TFLite model also has access to the normal TF model and, hence, can attack this model with foolbox.
