### ISSUE TITLE
specifying criterion fails with TypeError

### ISSUE THREAD

**Issue by rgeirhos** [bethgelab/foolbox#698]
**Describe the bug**
Attacks work when not specifying a criterion, however a TypeError is raised when specifying a criterion.
The minimal example uses FGM and TargetedMisclassification, however the behaviour is not specific to those: other attacks and other criteria (e.g. Misclassification) also result in the same TypeError.

I may be missing something obvious, but any pointers would be much appreciated!

**To Reproduce**
```python3

import torchvision.models as models
import torch
import eagerpy as ep
from foolbox import PyTorchModel, samples
from foolbox.attacks import FGM
from foolbox.criteria import TargetedMisclassification

model = models.resnet18(pretrained=True).eval()
preprocessing = dict(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], axis=-3)
fmodel = PyTorchModel(model, bounds=(0, 1), preprocessing=preprocessing)
images, labels = ep.astensors(*samples(fmodel, dataset="imagenet", batchsize=1))
epsilons = [0.1]
attack = FGM()

criterion = TargetedMisclassification(torch.tensor([42]))

raw_advs, clipped_advs, success = attack(fmodel, images, labels, epsilons=epsilons) 
# success

raw_advs, clipped_advs, success = attack(fmodel, images, labels, epsilons=epsilons, criterion=criterion)
# TypeError: FixedEpsilonAttack.__call__() got multiple values for argument 'criterion'
```

**Expected behavior**
No TypeError ("got multiple values for argument 'criterion'") raised when specifying a single criterion

**Software (please complete the following information):**
 - Foolbox version: 3.3.1
 -  PyTorch version (if applicable): 1.13.0
 -  TensorFlow version (if applicable): N/A
 -  JAX version (if applicable): N/A

**Comment by zimmerrol** [comment]
Hi, the error message shown is correct: you are passing the `criterion` argument twice - once as a positional and once as a keyword argument. Either remove `labels` from the attac kcall (to make make it a targeted attack) or remove `criterion=criterion` to make it an untargeted attack. Please let me know in case that doesn't solve your issue and feel free to open the issue again!

**Comment by rgeirhos** [comment]
Perfect, thanks for the clear & fast response! Happy to confirm that it's working.

(Just in case others stumble across this, I additionally had to to modify the minimal example from above with
 ```criterion = TargetedMisclassification(torch.LongTensor([42]))``` to make it run without errors, i.e. converting from torch.Tensor to torch.LongTensor)
