### ISSUE TITLE
Using Foolbox with Huggingface transfomers

### ISSUE THREAD

**Issue by bakachan19** [bethgelab/foolbox#736]
Hi,
I was wondering if is possible to use this library to attack Huggingface transformer models, for example the vit-base-patch16-224 model.
If so, could you provide a demo code for doing this?

Thank you.
Have a great day!

**Comment by zimmerrol** [comment]
I don't think one has to do something special about this, as that model is still a PyTorch model, no? In that case, the examples you can find online for using foolbox should apply.

**Comment by bakachan19** [comment]
I see, thank you.
I will give it a try and see how it works.
