### ISSUE TITLE
Can I use foolbox to generate adversarial examples for data that is not images but just some numeric integers?? I have to generate adversary examples for High performance counter data for malware detection. 

### ISSUE THREAD

**Issue by SaiRaj07** [bethgelab/foolbox#96]

**Comment by jonasrauber** [comment]
Copied from #80 

> In principle, it should be no problem to use Foolbox in this scenario. Image-specific things like the channel_axis argument can probably simply be ignored (they are only relevant for certain image-specific attacks). Same goes for arguments that have image-specific names (e.g. image, original_image), just use them as if they were named in a more generic way (we will fix this in a future version).

**Comment by SaiRaj07** [comment]
Hmm the jacobian method will be a good choice for generating adversary for numeric integers, and what changes will need to be made to make it a fit for numeric integers??

**Comment by jonasrauber** [comment]
Please be more concrete in describing your setting. I am happy to help, but it's impossible to understand what issues you exactly have. I recommend you start by defining your model, your input data and the type of misclassification you want to achieve.

**Comment by SaiRaj07** [comment]
Thanks. The attacks actually work on the numeric integers data. You just need to model the inputs as floats and they do the trick.
