### ISSUE TITLE
Inconsistency naming LBFGSBAttack / LBFGSAttack

### ISSUE THREAD

**Issue by berangerd** [bethgelab/foolbox#98]
The name LBFGSBAttack appears in several places in the doc, while it should be LBFGSAttack (see https://github.com/bethgelab/foolbox/search?utf8=%E2%9C%93&q=LBFGSBAttack&type=).

**Comment by jonasrauber** [comment]
Thanks @berangerd. The docs on http://foolbox.readthedocs.io/en/latest/ should be updated soon.
